// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_token.sql

package db

import (
	"context"
	"database/sql"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const findActiveAdminTokenByHash = `-- name: FindActiveAdminTokenByHash :one
SELECT id, token_hash, description, scopes, ip_allowlist,
       single_recharge_max, daily_recharge_quota_limit,
       single_refund_max, daily_refund_quota_limit,
       daily_account_create_limit, requests_per_minute, circuit_breaker_enabled,
       created_by, created_at, expires_at, revoked_at
FROM gateway_admin_token
WHERE token_hash = $1
  AND revoked_at IS NULL
  AND (expires_at IS NULL OR expires_at > NOW())
`

type FindActiveAdminTokenByHashRow struct {
	ID                      int64          `json:"id"`
	TokenHash               string         `json:"token_hash"`
	Description             string         `json:"description"`
	Scopes                  []string       `json:"scopes"`
	IpAllowlist             []netip.Prefix `json:"ip_allowlist"`
	SingleRechargeMax       pgtype.Int8    `json:"single_recharge_max"`
	DailyRechargeQuotaLimit pgtype.Int8    `json:"daily_recharge_quota_limit"`
	SingleRefundMax         pgtype.Int8    `json:"single_refund_max"`
	DailyRefundQuotaLimit   pgtype.Int8    `json:"daily_refund_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4    `json:"daily_account_create_limit"`
	RequestsPerMinute       pgtype.Int4    `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool           `json:"circuit_breaker_enabled"`
	CreatedBy               string         `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
	RevokedAt               sql.NullTime   `json:"revoked_at"`
}

// 鉴权热路径：根据 token_hash 单 query 查活跃 token（未 revoke + 未过期）。
// service 层调用前先算 hex = hex.EncodeToString(HMAC-SHA-256(pepper, plaintext))。
func (q *Queries) FindActiveAdminTokenByHash(ctx context.Context, tokenHash string) (FindActiveAdminTokenByHashRow, error) {
	row := q.db.QueryRow(ctx, findActiveAdminTokenByHash, tokenHash)
	var i FindActiveAdminTokenByHashRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.Scopes,
		&i.IpAllowlist,
		&i.SingleRechargeMax,
		&i.DailyRechargeQuotaLimit,
		&i.SingleRefundMax,
		&i.DailyRefundQuotaLimit,
		&i.DailyAccountCreateLimit,
		&i.RequestsPerMinute,
		&i.CircuitBreakerEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const findAdminTokenByID = `-- name: FindAdminTokenByID :one
SELECT id, token_hash, description, scopes, ip_allowlist,
       single_recharge_max, daily_recharge_quota_limit,
       single_refund_max, daily_refund_quota_limit,
       daily_account_create_limit, requests_per_minute, circuit_breaker_enabled,
       created_by, created_at, expires_at, revoked_at
FROM gateway_admin_token
WHERE id = $1
`

type FindAdminTokenByIDRow struct {
	ID                      int64          `json:"id"`
	TokenHash               string         `json:"token_hash"`
	Description             string         `json:"description"`
	Scopes                  []string       `json:"scopes"`
	IpAllowlist             []netip.Prefix `json:"ip_allowlist"`
	SingleRechargeMax       pgtype.Int8    `json:"single_recharge_max"`
	DailyRechargeQuotaLimit pgtype.Int8    `json:"daily_recharge_quota_limit"`
	SingleRefundMax         pgtype.Int8    `json:"single_refund_max"`
	DailyRefundQuotaLimit   pgtype.Int8    `json:"daily_refund_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4    `json:"daily_account_create_limit"`
	RequestsPerMinute       pgtype.Int4    `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool           `json:"circuit_breaker_enabled"`
	CreatedBy               string         `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
	RevokedAt               sql.NullTime   `json:"revoked_at"`
}

// 按 id 查 token（不限制是否 revoked / expired，运维查询用）。
func (q *Queries) FindAdminTokenByID(ctx context.Context, id int64) (FindAdminTokenByIDRow, error) {
	row := q.db.QueryRow(ctx, findAdminTokenByID, id)
	var i FindAdminTokenByIDRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.Scopes,
		&i.IpAllowlist,
		&i.SingleRechargeMax,
		&i.DailyRechargeQuotaLimit,
		&i.SingleRefundMax,
		&i.DailyRefundQuotaLimit,
		&i.DailyAccountCreateLimit,
		&i.RequestsPerMinute,
		&i.CircuitBreakerEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getCircuitState = `-- name: GetCircuitState :one
SELECT token_id, window_started_at, error_count, breaker_tripped_until,
       (breaker_tripped_until IS NOT NULL AND breaker_tripped_until > NOW()) AS is_tripped
FROM gateway_admin_token_circuit
WHERE token_id = $1
`

type GetCircuitStateRow struct {
	TokenID             int64        `json:"token_id"`
	WindowStartedAt     time.Time    `json:"window_started_at"`
	ErrorCount          int32        `json:"error_count"`
	BreakerTrippedUntil sql.NullTime `json:"breaker_tripped_until"`
	IsTripped           pgtype.Bool  `json:"is_tripped"`
}

// 查熔断器状态；middleware 在 CheckCircuitBreaker 时调用。
// 不存在 token_id 时返 0 rows（service 视作未熔断）。
func (q *Queries) GetCircuitState(ctx context.Context, tokenID int64) (GetCircuitStateRow, error) {
	row := q.db.QueryRow(ctx, getCircuitState, tokenID)
	var i GetCircuitStateRow
	err := row.Scan(
		&i.TokenID,
		&i.WindowStartedAt,
		&i.ErrorCount,
		&i.BreakerTrippedUntil,
		&i.IsTripped,
	)
	return i, err
}

const getTokenUsage = `-- name: GetTokenUsage :one
SELECT token_id, day, recharge_total_minor, refund_total_minor, account_create_count, updated_at
FROM gateway_admin_token_usage
WHERE token_id = $1
  AND day      = (NOW() AT TIME ZONE 'UTC')::date
`

// 查指定 token 当日用量；不存在则返 0 rows（service 层视作 0 用量）。
// day 同样按 UTC（与累加 query 对齐）。
func (q *Queries) GetTokenUsage(ctx context.Context, tokenID int64) (GatewayAdminTokenUsage, error) {
	row := q.db.QueryRow(ctx, getTokenUsage, tokenID)
	var i GatewayAdminTokenUsage
	err := row.Scan(
		&i.TokenID,
		&i.Day,
		&i.RechargeTotalMinor,
		&i.RefundTotalMinor,
		&i.AccountCreateCount,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTokenUsage = `-- name: IncrementTokenUsage :one


INSERT INTO gateway_admin_token_usage AS u (
    token_id, day,
    recharge_total_minor, refund_total_minor, account_create_count
)
VALUES (
    $1, (NOW() AT TIME ZONE 'UTC')::date,
    $2, $3, $4
)
ON CONFLICT (token_id, day) DO UPDATE
SET recharge_total_minor = u.recharge_total_minor + EXCLUDED.recharge_total_minor,
    refund_total_minor   = u.refund_total_minor   + EXCLUDED.refund_total_minor,
    account_create_count = u.account_create_count + EXCLUDED.account_create_count,
    updated_at           = NOW()
RETURNING token_id, day, recharge_total_minor, refund_total_minor, account_create_count, updated_at
`

type IncrementTokenUsageParams struct {
	TokenID            int64 `json:"token_id"`
	RechargeDelta      int64 `json:"recharge_delta"`
	RefundDelta        int64 `json:"refund_delta"`
	AccountCreateDelta int32 `json:"account_create_delta"`
}

// ============================================================================
// 2. Token 每日用量累计
// ============================================================================
// 单语句原子累加当日用量；不存在则 INSERT，存在则 UPDATE 累加。
// 三列分别累加（recharge / refund / create）；调用方按场景传非零的那一列，其他传 0。
// day 用 UTC 当日（决策 D9）。
func (q *Queries) IncrementTokenUsage(ctx context.Context, arg IncrementTokenUsageParams) (GatewayAdminTokenUsage, error) {
	row := q.db.QueryRow(ctx, incrementTokenUsage,
		arg.TokenID,
		arg.RechargeDelta,
		arg.RefundDelta,
		arg.AccountCreateDelta,
	)
	var i GatewayAdminTokenUsage
	err := row.Scan(
		&i.TokenID,
		&i.Day,
		&i.RechargeTotalMinor,
		&i.RefundTotalMinor,
		&i.AccountCreateCount,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAdminToken = `-- name: InsertAdminToken :one




INSERT INTO gateway_admin_token (
    token_hash, description, scopes, ip_allowlist,
    single_recharge_max, daily_recharge_quota_limit,
    single_refund_max, daily_refund_quota_limit,
    daily_account_create_limit, requests_per_minute, circuit_breaker_enabled,
    created_by, expires_at
)
VALUES (
    $1, $2, $3, $4,
    $5::bigint, $6::bigint,
    $7::bigint,   $8::bigint,
    $9::int, $10::int,
    $11,
    $12, $13::timestamptz
)
RETURNING id, token_hash, description, scopes, ip_allowlist,
          single_recharge_max, daily_recharge_quota_limit,
          single_refund_max, daily_refund_quota_limit,
          daily_account_create_limit, requests_per_minute, circuit_breaker_enabled,
          created_by, created_at, expires_at, revoked_at
`

type InsertAdminTokenParams struct {
	TokenHash               string         `json:"token_hash"`
	Description             string         `json:"description"`
	Scopes                  []string       `json:"scopes"`
	IpAllowlist             []netip.Prefix `json:"ip_allowlist"`
	SingleRechargeMax       pgtype.Int8    `json:"single_recharge_max"`
	DailyRechargeQuotaLimit pgtype.Int8    `json:"daily_recharge_quota_limit"`
	SingleRefundMax         pgtype.Int8    `json:"single_refund_max"`
	DailyRefundQuotaLimit   pgtype.Int8    `json:"daily_refund_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4    `json:"daily_account_create_limit"`
	RequestsPerMinute       pgtype.Int4    `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool           `json:"circuit_breaker_enabled"`
	CreatedBy               string         `json:"created_by"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
}

type InsertAdminTokenRow struct {
	ID                      int64          `json:"id"`
	TokenHash               string         `json:"token_hash"`
	Description             string         `json:"description"`
	Scopes                  []string       `json:"scopes"`
	IpAllowlist             []netip.Prefix `json:"ip_allowlist"`
	SingleRechargeMax       pgtype.Int8    `json:"single_recharge_max"`
	DailyRechargeQuotaLimit pgtype.Int8    `json:"daily_recharge_quota_limit"`
	SingleRefundMax         pgtype.Int8    `json:"single_refund_max"`
	DailyRefundQuotaLimit   pgtype.Int8    `json:"daily_refund_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4    `json:"daily_account_create_limit"`
	RequestsPerMinute       pgtype.Int4    `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool           `json:"circuit_breaker_enabled"`
	CreatedBy               string         `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
	RevokedAt               sql.NullTime   `json:"revoked_at"`
}

// admin_token.sql —— Admin Token CRUD + 阀门用量累计 + 熔断器状态机
//
// 设计文档：docs/multimedia-gateway-design.md §9bis.6（Admin Token 安全 5 件套）
// 实施计划：docs/plans/2026-05-27-003-feat-workflow-d-min-admin-api-plan.md Unit 1
//
// 命名约定：
//   - InsertAdminToken / FindActiveAdminTokenByHash / RevokeAdminToken / ListActiveAdminTokens：token CRUD
//   - IncrementTokenUsage / GetTokenUsage：每日用量累计 + 查询
//   - RecordCircuitError / TripCircuitBreaker / GetCircuitState / ResetCircuitBreaker：熔断器状态机
//
// 关键 PG 语义：
//   - ON CONFLICT DO UPDATE：用于 UPSERT 同行原子累加，行锁串行化保证 100+ 并发同行无丢失
//   - COALESCE(revoked_at, NOW())：Revoke 同 token 多次时保留首次 revoke 时间戳，幂等成功
//   - CASE WHEN 在 DO UPDATE SET 子句中：实现 circuit 1h 滚动窗口的"超时即重置"
//
// ============================================================================
// 1. Admin Token CRUD
// ============================================================================
// 插入新 Admin Token；调用方负责生成 plaintext + HMAC-SHA-256(pepper, plaintext) → token_hash hex。
// 7 个阀门字段 NULL = 无限制；ip_allowlist 至少 1 个 CIDR（service 层校验，schema 不强制）。
func (q *Queries) InsertAdminToken(ctx context.Context, arg InsertAdminTokenParams) (InsertAdminTokenRow, error) {
	row := q.db.QueryRow(ctx, insertAdminToken,
		arg.TokenHash,
		arg.Description,
		arg.Scopes,
		arg.IpAllowlist,
		arg.SingleRechargeMax,
		arg.DailyRechargeQuotaLimit,
		arg.SingleRefundMax,
		arg.DailyRefundQuotaLimit,
		arg.DailyAccountCreateLimit,
		arg.RequestsPerMinute,
		arg.CircuitBreakerEnabled,
		arg.CreatedBy,
		arg.ExpiresAt,
	)
	var i InsertAdminTokenRow
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.Description,
		&i.Scopes,
		&i.IpAllowlist,
		&i.SingleRechargeMax,
		&i.DailyRechargeQuotaLimit,
		&i.SingleRefundMax,
		&i.DailyRefundQuotaLimit,
		&i.DailyAccountCreateLimit,
		&i.RequestsPerMinute,
		&i.CircuitBreakerEnabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const listActiveAdminTokens = `-- name: ListActiveAdminTokens :many
SELECT id, description, scopes, ip_allowlist,
       single_recharge_max, daily_recharge_quota_limit,
       single_refund_max, daily_refund_quota_limit,
       daily_account_create_limit, requests_per_minute, circuit_breaker_enabled,
       created_by, created_at, expires_at, revoked_at
FROM gateway_admin_token
WHERE revoked_at IS NULL
ORDER BY created_at DESC
`

type ListActiveAdminTokensRow struct {
	ID                      int64          `json:"id"`
	Description             string         `json:"description"`
	Scopes                  []string       `json:"scopes"`
	IpAllowlist             []netip.Prefix `json:"ip_allowlist"`
	SingleRechargeMax       pgtype.Int8    `json:"single_recharge_max"`
	DailyRechargeQuotaLimit pgtype.Int8    `json:"daily_recharge_quota_limit"`
	SingleRefundMax         pgtype.Int8    `json:"single_refund_max"`
	DailyRefundQuotaLimit   pgtype.Int8    `json:"daily_refund_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4    `json:"daily_account_create_limit"`
	RequestsPerMinute       pgtype.Int4    `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool           `json:"circuit_breaker_enabled"`
	CreatedBy               string         `json:"created_by"`
	CreatedAt               time.Time      `json:"created_at"`
	ExpiresAt               sql.NullTime   `json:"expires_at"`
	RevokedAt               sql.NullTime   `json:"revoked_at"`
}

// 列出所有活跃 token（未 revoke）；按 created_at DESC 排序便于运维查最新发放。
// 返回**不含** token_hash（避免泄漏；明文已无法获取，hash 也只入审计 / 排查路径）。
func (q *Queries) ListActiveAdminTokens(ctx context.Context) ([]ListActiveAdminTokensRow, error) {
	rows, err := q.db.Query(ctx, listActiveAdminTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveAdminTokensRow{}
	for rows.Next() {
		var i ListActiveAdminTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Description,
			&i.Scopes,
			&i.IpAllowlist,
			&i.SingleRechargeMax,
			&i.DailyRechargeQuotaLimit,
			&i.SingleRefundMax,
			&i.DailyRefundQuotaLimit,
			&i.DailyAccountCreateLimit,
			&i.RequestsPerMinute,
			&i.CircuitBreakerEnabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCircuitError = `-- name: RecordCircuitError :one


INSERT INTO gateway_admin_token_circuit (token_id, window_started_at, error_count)
VALUES ($1, NOW(), 1)
ON CONFLICT (token_id) DO UPDATE
SET error_count = CASE
        WHEN gateway_admin_token_circuit.window_started_at < NOW() - INTERVAL '1 hour'
        THEN 1
        ELSE gateway_admin_token_circuit.error_count + 1
    END,
    window_started_at = CASE
        WHEN gateway_admin_token_circuit.window_started_at < NOW() - INTERVAL '1 hour'
        THEN NOW()
        ELSE gateway_admin_token_circuit.window_started_at
    END,
    updated_at = NOW()
RETURNING token_id, window_started_at, error_count, breaker_tripped_until
`

type RecordCircuitErrorRow struct {
	TokenID             int64        `json:"token_id"`
	WindowStartedAt     time.Time    `json:"window_started_at"`
	ErrorCount          int32        `json:"error_count"`
	BreakerTrippedUntil sql.NullTime `json:"breaker_tripped_until"`
}

// ============================================================================
// 3. 熔断器状态机
// ============================================================================
// 错误计数 + 1h 滚动窗口自动重置（document-review feasibility #8 完整 SQL）。
// 行为：
//   - 不存在 token_id → INSERT (window_started_at=NOW(), error_count=1)
//   - 存在但 window_started_at < NOW() - 1h → 重置窗口（error_count=1, window_started_at=NOW()）
//   - 存在且窗口内 → error_count + 1
//
// 单语句完成所有路径，行锁串行化保证 50+ 并发同 token error_count 最终 = 实际错误数。
func (q *Queries) RecordCircuitError(ctx context.Context, tokenID int64) (RecordCircuitErrorRow, error) {
	row := q.db.QueryRow(ctx, recordCircuitError, tokenID)
	var i RecordCircuitErrorRow
	err := row.Scan(
		&i.TokenID,
		&i.WindowStartedAt,
		&i.ErrorCount,
		&i.BreakerTrippedUntil,
	)
	return i, err
}

const resetCircuitBreaker = `-- name: ResetCircuitBreaker :one
UPDATE gateway_admin_token_circuit
SET breaker_tripped_until = NULL,
    error_count           = 0,
    window_started_at     = NOW(),
    updated_at            = NOW()
WHERE token_id = $1
RETURNING token_id, window_started_at, error_count, breaker_tripped_until
`

type ResetCircuitBreakerRow struct {
	TokenID             int64        `json:"token_id"`
	WindowStartedAt     time.Time    `json:"window_started_at"`
	ErrorCount          int32        `json:"error_count"`
	BreakerTrippedUntil sql.NullTime `json:"breaker_tripped_until"`
}

// 运维手工解锁熔断器（admin-cli circuit-reset 推 P1）。
// 重置 error_count 与 window，清 breaker_tripped_until。
func (q *Queries) ResetCircuitBreaker(ctx context.Context, tokenID int64) (ResetCircuitBreakerRow, error) {
	row := q.db.QueryRow(ctx, resetCircuitBreaker, tokenID)
	var i ResetCircuitBreakerRow
	err := row.Scan(
		&i.TokenID,
		&i.WindowStartedAt,
		&i.ErrorCount,
		&i.BreakerTrippedUntil,
	)
	return i, err
}

const revokeAdminToken = `-- name: RevokeAdminToken :one
UPDATE gateway_admin_token
SET revoked_at = COALESCE(revoked_at, NOW())
WHERE id = $1
RETURNING id, revoked_at
`

type RevokeAdminTokenRow struct {
	ID        int64        `json:"id"`
	RevokedAt sql.NullTime `json:"revoked_at"`
}

// Revoke 给定 id 的 token。
// 用 COALESCE(revoked_at, NOW()) 保留首次 revoke 时间戳，多次 Revoke 同 id 不覆盖原 timestamp。
// 返回值（id + 新 revoked_at + 原 revoked_at）让 service 区分"首次 revoke" vs "已 revoked 幂等"。
// 不存在 id 时返 0 rows（service 层判 ErrTokenNotFound）。
func (q *Queries) RevokeAdminToken(ctx context.Context, id int64) (RevokeAdminTokenRow, error) {
	row := q.db.QueryRow(ctx, revokeAdminToken, id)
	var i RevokeAdminTokenRow
	err := row.Scan(&i.ID, &i.RevokedAt)
	return i, err
}

const tripCircuitBreaker = `-- name: TripCircuitBreaker :one
UPDATE gateway_admin_token_circuit
SET breaker_tripped_until = GREATEST(COALESCE(breaker_tripped_until, NOW()), NOW() + INTERVAL '1 hour'),
    updated_at = NOW()
WHERE token_id = $1
RETURNING token_id, window_started_at, error_count, breaker_tripped_until
`

type TripCircuitBreakerRow struct {
	TokenID             int64        `json:"token_id"`
	WindowStartedAt     time.Time    `json:"window_started_at"`
	ErrorCount          int32        `json:"error_count"`
	BreakerTrippedUntil sql.NullTime `json:"breaker_tripped_until"`
}

// 跳闸：把 breaker_tripped_until 写为 NOW() + 1h；service 在 RecordCircuitError 返 error_count ≥ 100 时调。
// 已跳闸 token 重复调用：tripped_until 取较大值（不会缩短跳闸期）。
func (q *Queries) TripCircuitBreaker(ctx context.Context, tokenID int64) (TripCircuitBreakerRow, error) {
	row := q.db.QueryRow(ctx, tripCircuitBreaker, tokenID)
	var i TripCircuitBreakerRow
	err := row.Scan(
		&i.TokenID,
		&i.WindowStartedAt,
		&i.ErrorCount,
		&i.BreakerTrippedUntil,
	)
	return i, err
}
