// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admin_session.sql

package db

import (
	"context"
	"time"
)

const deleteAdminSessionByTokenHash = `-- name: DeleteAdminSessionByTokenHash :execrows
DELETE FROM admin_session
WHERE session_token_hash = $1
`

// 登出：按 token_hash 删会话；返回受影响行数（0 = 会话已不存在，幂等）。
func (q *Queries) DeleteAdminSessionByTokenHash(ctx context.Context, sessionTokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminSessionByTokenHash, sessionTokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAdminSessionsByOperator = `-- name: DeleteAdminSessionsByOperator :execrows
DELETE FROM admin_session
WHERE operator_id = $1
`

// 禁用账户 / 强制下线：删某运维全部会话。
func (q *Queries) DeleteAdminSessionsByOperator(ctx context.Context, operatorID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAdminSessionsByOperator, operatorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteExpiredAdminSessions = `-- name: DeleteExpiredAdminSessions :execrows
DELETE FROM admin_session
WHERE expires_at <= NOW()
`

// sweep：清理已过期会话（后台定期调用）。
func (q *Queries) DeleteExpiredAdminSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAdminSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveAdminSessionByTokenHash = `-- name: GetActiveAdminSessionByTokenHash :one
SELECT s.id            AS session_id,
       s.operator_id   AS operator_id,
       s.csrf_token    AS csrf_token,
       s.expires_at    AS expires_at,
       o.username      AS username,
       o.enabled       AS operator_enabled
FROM admin_session s
JOIN operator_account o ON o.id = s.operator_id
WHERE s.session_token_hash = $1
  AND s.expires_at > NOW()
  AND o.enabled = true
`

type GetActiveAdminSessionByTokenHashRow struct {
	SessionID       int64     `json:"session_id"`
	OperatorID      int64     `json:"operator_id"`
	CsrfToken       string    `json:"csrf_token"`
	ExpiresAt       time.Time `json:"expires_at"`
	Username        string    `json:"username"`
	OperatorEnabled bool      `json:"operator_enabled"`
}

// 鉴权热路径：按 token_hash 取**未过期 + 账户启用**的会话，并带出运维身份。
// 任一不满足（无会话 / 已过期 / 账户禁用）→ 0 rows → 中间件 fail-closed 401。
func (q *Queries) GetActiveAdminSessionByTokenHash(ctx context.Context, sessionTokenHash string) (GetActiveAdminSessionByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveAdminSessionByTokenHash, sessionTokenHash)
	var i GetActiveAdminSessionByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.OperatorID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.Username,
		&i.OperatorEnabled,
	)
	return i, err
}

const insertAdminSession = `-- name: InsertAdminSession :one


INSERT INTO admin_session (session_token_hash, operator_id, csrf_token, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, operator_id, csrf_token, expires_at, created_at
`

type InsertAdminSessionParams struct {
	SessionTokenHash string    `json:"session_token_hash"`
	OperatorID       int64     `json:"operator_id"`
	CsrfToken        string    `json:"csrf_token"`
	ExpiresAt        time.Time `json:"expires_at"`
}

type InsertAdminSessionRow struct {
	ID         int64     `json:"id"`
	OperatorID int64     `json:"operator_id"`
	CsrfToken  string    `json:"csrf_token"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

// admin_session.sql —— 管理后台 PG 会话 CRUD + 鉴权热路径
//
// 决策依据：ADR-0008（会话存 PG；存 token 的 HMAC 而非明文）
// 实施计划：docs/plans/2026-05-31-001-feat-admin-console-config-plan.md Unit 2（供 Unit 4 会话中间件）
//
// 安全约定：
//   - session_token_hash = HMAC(pepper, 会话明文 token) hex；明文只在 HttpOnly Cookie。
//   - 鉴权按 token_hash 单 row 查 + 校验 expires_at > NOW() + 账户 enabled。
//
// 登录成功建会话；session_token_hash / csrf_token / expires_at 由 service 层（Unit 4）算好传入。
func (q *Queries) InsertAdminSession(ctx context.Context, arg InsertAdminSessionParams) (InsertAdminSessionRow, error) {
	row := q.db.QueryRow(ctx, insertAdminSession,
		arg.SessionTokenHash,
		arg.OperatorID,
		arg.CsrfToken,
		arg.ExpiresAt,
	)
	var i InsertAdminSessionRow
	err := row.Scan(
		&i.ID,
		&i.OperatorID,
		&i.CsrfToken,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const touchAdminSessionLastSeen = `-- name: TouchAdminSessionLastSeen :exec
UPDATE admin_session
SET last_seen_at = NOW()
WHERE id = $1
`

// 异步 best-effort 更新 last_seen_at（审计 / 可选续期）；失败不影响鉴权主路径。
func (q *Queries) TouchAdminSessionLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAdminSessionLastSeen, id)
	return err
}
