// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: balance.sql

package db

import (
	"context"
	"database/sql"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalance = `-- name: GetBalance :one


SELECT business_account_id, available, reserved, used_total, recharge_total,
       refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
FROM business_account_balance
WHERE business_account_id = $1
`

// balance.sql —— 账户余额投影读取
//
// 写路径由 ledger.sql 的 CTE 单语句完成（INSERT ledger + UPDATE balance）；
// 本文件仅承载读路径 + rebuild 专用的 ReplaceBalance（绕过 CAS 的写）。
// 标准读取：用于 service.GetBalance + admin-cli 反查 + 测试断言。
func (q *Queries) GetBalance(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, getBalance, businessAccountID)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT business_account_id, available, reserved, used_total, recharge_total,
       refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
FROM business_account_balance
WHERE business_account_id = $1
FOR UPDATE
`

// 行级 FOR UPDATE 读：rebuild TX3 用，防并发 Commit/Release 写入。
func (q *Queries) GetBalanceForUpdate(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, businessAccountID)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const getBalanceInTx = `-- name: GetBalanceInTx :one
SELECT business_account_id, available, reserved, used_total, recharge_total,
       refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
FROM business_account_balance
WHERE business_account_id = $1
`

// 事务内读取：与 GetBalance 等价，但显式由 service 在 CAS 失败后的同一 tx 调用。
// 保留独立 query 命名，便于 grep 出「事务内读」语义。
func (q *Queries) GetBalanceInTx(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, getBalanceInTx, businessAccountID)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const listAllUnfrozenAccountsForReconciler = `-- name: ListAllUnfrozenAccountsForReconciler :many
SELECT business_account_id, version
FROM business_account_balance
WHERE frozen = false
ORDER BY business_account_id ASC
`

type ListAllUnfrozenAccountsForReconcilerRow struct {
	BusinessAccountID string `json:"business_account_id"`
	Version           int64  `json:"version"`
}

// reconciler 全表扫起点：仅取 ID + 当前 version；后续读 SUM 时再单只读 tx 中拉一致快照。
func (q *Queries) ListAllUnfrozenAccountsForReconciler(ctx context.Context) ([]ListAllUnfrozenAccountsForReconcilerRow, error) {
	rows, err := q.db.Query(ctx, listAllUnfrozenAccountsForReconciler)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllUnfrozenAccountsForReconcilerRow{}
	for rows.Next() {
		var i ListAllUnfrozenAccountsForReconcilerRow
		if err := rows.Scan(&i.BusinessAccountID, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckRebuildAccounts = `-- name: ListStuckRebuildAccounts :many
SELECT business_account_id, frozen_at
FROM business_account_balance
WHERE frozen = true
  AND frozen_reason LIKE '%rebuild_in_progress%'
  AND frozen_at IS NOT NULL
  AND frozen_at < (NOW() - $1::interval)
`

type ListStuckRebuildAccountsRow struct {
	BusinessAccountID string       `json:"business_account_id"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
}

// reconciler 收尾 watchdog：扫出处于 rebuild_in_progress 状态且 frozen 时间过长的账户。
//
// 用途：U8 RebuildBalance 三事务流程中第二阶段崩溃 / 进程被 kill 时，账户会停留在
// frozen=true + reason 含 'rebuild_in_progress' 状态；本查询给 reconciler 暴露 metric
// 让运维及时发现并人工恢复（pass-2 sec sec-pass2-008）。
//
// @threshold 参数取自 reconciler.rebuildStuckThreshold（默认 10 分钟）。
func (q *Queries) ListStuckRebuildAccounts(ctx context.Context, threshold pgtype.Interval) ([]ListStuckRebuildAccountsRow, error) {
	rows, err := q.db.Query(ctx, listStuckRebuildAccounts, threshold)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStuckRebuildAccountsRow{}
	for rows.Next() {
		var i ListStuckRebuildAccountsRow
		if err := rows.Scan(&i.BusinessAccountID, &i.FrozenAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceBalance = `-- name: ReplaceBalance :execrows
UPDATE business_account_balance
SET available      = $1,
    reserved       = $2,
    used_total     = $3,
    recharge_total = $4,
    refund_total   = $5,
    version        = version + 1,
    updated_at     = NOW()
WHERE business_account_id = $6
  AND last_ledger_id     = $7
`

type ReplaceBalanceParams struct {
	Available            int64  `json:"available"`
	Reserved             int64  `json:"reserved"`
	UsedTotal            int64  `json:"used_total"`
	RechargeTotal        int64  `json:"recharge_total"`
	RefundTotal          int64  `json:"refund_total"`
	BusinessAccountID    string `json:"business_account_id"`
	ExpectedLastLedgerID int64  `json:"expected_last_ledger_id"`
}

// rebuild TX3 专用：用 last_ledger_id CAS 校验「TX2 读快照后没有新 entry 写入」；
// 命中行数 = 0 表示并发漂移，调用方应回到 TX2 重读快照。
// 不参与日常写路径，绕开 version CAS（rebuild 期间 frozen=true 已阻新业务写）。
func (q *Queries) ReplaceBalance(ctx context.Context, arg ReplaceBalanceParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceBalance,
		arg.Available,
		arg.Reserved,
		arg.UsedTotal,
		arg.RechargeTotal,
		arg.RefundTotal,
		arg.BusinessAccountID,
		arg.ExpectedLastLedgerID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
