// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: business_account.sql

package db

import (
	"context"
)

const createBusinessAccount = `-- name: CreateBusinessAccount :one


INSERT INTO business_account (
    id, status, isolation_required, metadata
) VALUES (
    $1, 'active', $2, $3
)
RETURNING id, status, isolation_required, break_glass_until, metadata, created_at, updated_at
`

type CreateBusinessAccountParams struct {
	ID                string `json:"id"`
	IsolationRequired bool   `json:"isolation_required"`
	Metadata          []byte `json:"metadata"`
}

// business_account.sql —— 业务账户 CRUD
//
// 适用范围：账户创建（同事务建 balance 行）/ 读取 / 入口 active 校验。
// 实现层：internal/ledger/postgres.go CreateAccount + 通用查询。
//
// 说明：CreateBusinessAccount 仅插入 business_account 主表；
//
//	同事务的 business_account_balance(zeros) 由调用方在同一 pgx.Tx 中
//	另起一条 INSERT（详见 ledger.sql 与 service 实现），便于复用 BalanceRow。
//
// 创建业务账户主记录；调用方负责在同一事务内插入 balance(zeros) 与 outbox 事件。
func (q *Queries) CreateBusinessAccount(ctx context.Context, arg CreateBusinessAccountParams) (BusinessAccount, error) {
	row := q.db.QueryRow(ctx, createBusinessAccount, arg.ID, arg.IsolationRequired, arg.Metadata)
	var i BusinessAccount
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.IsolationRequired,
		&i.BreakGlassUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBusinessAccountBalanceZero = `-- name: CreateBusinessAccountBalanceZero :one
INSERT INTO business_account_balance (
    business_account_id,
    available, reserved, used_total, recharge_total, refund_total,
    version, frozen, last_ledger_id
) VALUES (
    $1,
    0, 0, 0, 0, 0,
    0, false, 0
)
RETURNING business_account_id, available, reserved, used_total, recharge_total,
          refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
`

// 创建账户的零值 balance 行（与 CreateBusinessAccount 同事务）。
func (q *Queries) CreateBusinessAccountBalanceZero(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, createBusinessAccountBalanceZero, businessAccountID)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const getBusinessAccount = `-- name: GetBusinessAccount :one
SELECT id, status, isolation_required, break_glass_until, metadata, created_at, updated_at
FROM business_account
WHERE id = $1
`

// 读取业务账户主记录（用于反查 / 管理后台展示）。
func (q *Queries) GetBusinessAccount(ctx context.Context, id string) (BusinessAccount, error) {
	row := q.db.QueryRow(ctx, getBusinessAccount, id)
	var i BusinessAccount
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.IsolationRequired,
		&i.BreakGlassUntil,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBusinessAccountForActiveCheck = `-- name: GetBusinessAccountForActiveCheck :one
SELECT status, isolation_required
FROM business_account
WHERE id = $1
`

type GetBusinessAccountForActiveCheckRow struct {
	Status            BusinessAccountStatus `json:"status"`
	IsolationRequired bool                  `json:"isolation_required"`
}

// 入口校验：仅返回 status + isolation_required，避免拉全字段；
// service 层在写操作入口先调用此 query 判 status='active'。
func (q *Queries) GetBusinessAccountForActiveCheck(ctx context.Context, id string) (GetBusinessAccountForActiveCheckRow, error) {
	row := q.db.QueryRow(ctx, getBusinessAccountForActiveCheck, id)
	var i GetBusinessAccountForActiveCheckRow
	err := row.Scan(&i.Status, &i.IsolationRequired)
	return i, err
}
