// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: channel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChannel = `-- name: DeleteChannel :execrows
DELETE FROM channel WHERE id = $1
`

// 硬删除渠道（运营慎用；返回受影响行数判断是否存在）。
func (q *Queries) DeleteChannel(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChannel, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getChannelByID = `-- name: GetChannelByID :one
SELECT id, name, provider_type, enabled, restricted_business_accounts, channel_purpose, credentials_encrypted, key_version, other_settings, created_at, updated_at FROM channel WHERE id = $1
`

// 按 id 查渠道（含密文；service 层即用即解、不回显明文）。
func (q *Queries) GetChannelByID(ctx context.Context, id int64) (Channel, error) {
	row := q.db.QueryRow(ctx, getChannelByID, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Enabled,
		&i.RestrictedBusinessAccounts,
		&i.ChannelPurpose,
		&i.CredentialsEncrypted,
		&i.KeyVersion,
		&i.OtherSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertChannel = `-- name: InsertChannel :one


INSERT INTO channel (
    name, provider_type, enabled,
    restricted_business_accounts, channel_purpose,
    credentials_encrypted, key_version, other_settings
)
VALUES (
    $1, $2, $3,
    $4, $5,
    $6, $7, $8
)
RETURNING id, name, provider_type, enabled, restricted_business_accounts, channel_purpose, credentials_encrypted, key_version, other_settings, created_at, updated_at
`

type InsertChannelParams struct {
	Name                       string      `json:"name"`
	ProviderType               string      `json:"provider_type"`
	Enabled                    bool        `json:"enabled"`
	RestrictedBusinessAccounts []string    `json:"restricted_business_accounts"`
	ChannelPurpose             pgtype.Text `json:"channel_purpose"`
	CredentialsEncrypted       []byte      `json:"credentials_encrypted"`
	KeyVersion                 int32       `json:"key_version"`
	OtherSettings              []byte      `json:"other_settings"`
}

// channel.sql —— 渠道（上游 provider 凭据抽象）CRUD + 路由热路径查询
//
// 设计文档：docs/multimedia-gateway-design.md §8.2
// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 3 channel service）
//
// 安全约定：credentials_encrypted 是 envelope 密文（AES-GCM，KEK），明文绝不入库；
//
//	key_version 标记加密用的 KEK 版本，支持轮换（ADR-0006 决策 4）。
//
// 创建渠道；credentials_encrypted 由 service 层（Unit 3）用 KEK 加密后传入。
func (q *Queries) InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error) {
	row := q.db.QueryRow(ctx, insertChannel,
		arg.Name,
		arg.ProviderType,
		arg.Enabled,
		arg.RestrictedBusinessAccounts,
		arg.ChannelPurpose,
		arg.CredentialsEncrypted,
		arg.KeyVersion,
		arg.OtherSettings,
	)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Enabled,
		&i.RestrictedBusinessAccounts,
		&i.ChannelPurpose,
		&i.CredentialsEncrypted,
		&i.KeyVersion,
		&i.OtherSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveChannels = `-- name: ListActiveChannels :many
SELECT id, name, provider_type, enabled, restricted_business_accounts, channel_purpose, credentials_encrypted, key_version, other_settings, created_at, updated_at FROM channel
WHERE enabled = true
ORDER BY id
`

// 列出所有启用的渠道（路由候选 / 运营列表）。
func (q *Queries) ListActiveChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listActiveChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Enabled,
			&i.RestrictedBusinessAccounts,
			&i.ChannelPurpose,
			&i.CredentialsEncrypted,
			&i.KeyVersion,
			&i.OtherSettings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveChannelsByProvider = `-- name: ListActiveChannelsByProvider :many
SELECT id, name, provider_type, enabled, restricted_business_accounts, channel_purpose, credentials_encrypted, key_version, other_settings, created_at, updated_at FROM channel
WHERE provider_type = $1
  AND enabled = true
ORDER BY id
`

// 按 provider_type 列出启用的渠道（工厂按 provider 选 adapter 时用）。
func (q *Queries) ListActiveChannelsByProvider(ctx context.Context, providerType string) ([]Channel, error) {
	rows, err := q.db.Query(ctx, listActiveChannelsByProvider, providerType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Channel{}
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProviderType,
			&i.Enabled,
			&i.RestrictedBusinessAccounts,
			&i.ChannelPurpose,
			&i.CredentialsEncrypted,
			&i.KeyVersion,
			&i.OtherSettings,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChannelEnabled = `-- name: SetChannelEnabled :one
UPDATE channel
SET enabled    = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, enabled
`

type SetChannelEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

type SetChannelEnabledRow struct {
	ID      int64 `json:"id"`
	Enabled bool  `json:"enabled"`
}

// 启用 / 停用渠道（软下线优先于硬删除）。
func (q *Queries) SetChannelEnabled(ctx context.Context, arg SetChannelEnabledParams) (SetChannelEnabledRow, error) {
	row := q.db.QueryRow(ctx, setChannelEnabled, arg.Enabled, arg.ID)
	var i SetChannelEnabledRow
	err := row.Scan(&i.ID, &i.Enabled)
	return i, err
}

const updateChannelCredentials = `-- name: UpdateChannelCredentials :one
UPDATE channel
SET credentials_encrypted = $1,
    key_version           = $2,
    updated_at            = NOW()
WHERE id = $3
RETURNING id, name, provider_type, enabled, restricted_business_accounts, channel_purpose, credentials_encrypted, key_version, other_settings, created_at, updated_at
`

type UpdateChannelCredentialsParams struct {
	CredentialsEncrypted []byte `json:"credentials_encrypted"`
	KeyVersion           int32  `json:"key_version"`
	ID                   int64  `json:"id"`
}

// 更新渠道凭据密文 + KEK 版本（凭据轮换 / KEK 重加密命令用，ADR-0006 决策 4）。
// 仅动密文与版本，不碰其他配置；明文绝不入库。
func (q *Queries) UpdateChannelCredentials(ctx context.Context, arg UpdateChannelCredentialsParams) (Channel, error) {
	row := q.db.QueryRow(ctx, updateChannelCredentials, arg.CredentialsEncrypted, arg.KeyVersion, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProviderType,
		&i.Enabled,
		&i.RestrictedBusinessAccounts,
		&i.ChannelPurpose,
		&i.CredentialsEncrypted,
		&i.KeyVersion,
		&i.OtherSettings,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
