// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entitlement.sql

package db

import (
	"context"
)

const checkEntitlement = `-- name: CheckEntitlement :one
SELECT EXISTS (
    SELECT 1 FROM business_account_model_entitlement
    WHERE business_account_id = $1
      AND gateway_model = $2
) AS entitled
`

type CheckEntitlementParams struct {
	BusinessAccountID string `json:"business_account_id"`
	GatewayModel      string `json:"gateway_model"`
}

// 鉴权热路径：账户是否被授权使用该 model（提交前校验）。
func (q *Queries) CheckEntitlement(ctx context.Context, arg CheckEntitlementParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkEntitlement, arg.BusinessAccountID, arg.GatewayModel)
	var entitled bool
	err := row.Scan(&entitled)
	return entitled, err
}

const grantEntitlement = `-- name: GrantEntitlement :one


INSERT INTO business_account_model_entitlement (business_account_id, gateway_model)
VALUES ($1, $2)
ON CONFLICT (business_account_id, gateway_model) DO UPDATE
    SET updated_at = NOW()
RETURNING business_account_id, gateway_model, created_at, updated_at
`

type GrantEntitlementParams struct {
	BusinessAccountID string `json:"business_account_id"`
	GatewayModel      string `json:"gateway_model"`
}

// entitlement.sql —— 账户×模型授权 grant / revoke / check
//
// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 10/11）
// 语义：行存在 = 已授权；revoke = 删行；check = 存在性。复合主键 (account, gateway_model)。
// 授权账户使用某 gateway model；幂等（重复 grant 仅刷新 updated_at，不报错）。
func (q *Queries) GrantEntitlement(ctx context.Context, arg GrantEntitlementParams) (BusinessAccountModelEntitlement, error) {
	row := q.db.QueryRow(ctx, grantEntitlement, arg.BusinessAccountID, arg.GatewayModel)
	var i BusinessAccountModelEntitlement
	err := row.Scan(
		&i.BusinessAccountID,
		&i.GatewayModel,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntitlementsByAccount = `-- name: ListEntitlementsByAccount :many
SELECT business_account_id, gateway_model, created_at, updated_at FROM business_account_model_entitlement
WHERE business_account_id = $1
ORDER BY gateway_model
`

// 列出账户的全部授权 model（admin / 运维）。
func (q *Queries) ListEntitlementsByAccount(ctx context.Context, businessAccountID string) ([]BusinessAccountModelEntitlement, error) {
	rows, err := q.db.Query(ctx, listEntitlementsByAccount, businessAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BusinessAccountModelEntitlement{}
	for rows.Next() {
		var i BusinessAccountModelEntitlement
		if err := rows.Scan(
			&i.BusinessAccountID,
			&i.GatewayModel,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeEntitlement = `-- name: RevokeEntitlement :execrows
DELETE FROM business_account_model_entitlement
WHERE business_account_id = $1
  AND gateway_model = $2
`

type RevokeEntitlementParams struct {
	BusinessAccountID string `json:"business_account_id"`
	GatewayModel      string `json:"gateway_model"`
}

// 撤销授权（删行）；返回受影响行数判断是否原本存在。
func (q *Queries) RevokeEntitlement(ctx context.Context, arg RevokeEntitlementParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeEntitlement, arg.BusinessAccountID, arg.GatewayModel)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
