// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const commitAtomic = `-- name: CommitAtomic :one
WITH new_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'commit', $2,
        0, (0::bigint - $2)::bigint, $2,
        $3, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET reserved       = reserved - $10,
        used_total     = used_total + $2,
        last_ledger_id = (SELECT id FROM new_entry),
        version        = version + 1,
        updated_at     = NOW()
    WHERE business_account_id = $1
      AND version             = $11
      AND reserved            >= $10
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM new_entry)         AS new_ledger_id,
    (SELECT created_at FROM new_entry) AS new_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type CommitAtomicParams struct {
	BusinessAccountID string      `json:"business_account_id"`
	ActualCost        int64       `json:"actual_cost"`
	CorrelationID     string      `json:"correlation_id"`
	Snapshot          []byte      `json:"snapshot"`
	ReferenceType     pgtype.Text `json:"reference_type"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	Metadata          []byte      `json:"metadata"`
	ActorType         ActorType   `json:"actor_type"`
	ActorID           string      `json:"actor_id"`
	ReserveAmount     int64       `json:"reserve_amount"`
	ExpectedVersion   int64       `json:"expected_version"`
}

type CommitAtomicRow struct {
	NewLedgerID       int64        `json:"new_ledger_id"`
	NewCreatedAt      time.Time    `json:"new_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// 结算（无残余，actualCost == reserveAmount）：只 INSERT commit + UPDATE balance。
// 与 CommitWithReleaseAtomic 同语义，但少一条 release entry，sqlc 类型推导更干净。
func (q *Queries) CommitAtomic(ctx context.Context, arg CommitAtomicParams) (CommitAtomicRow, error) {
	row := q.db.QueryRow(ctx, commitAtomic,
		arg.BusinessAccountID,
		arg.ActualCost,
		arg.CorrelationID,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ReserveAmount,
		arg.ExpectedVersion,
	)
	var i CommitAtomicRow
	err := row.Scan(
		&i.NewLedgerID,
		&i.NewCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const commitWithReleaseAtomic = `-- name: CommitWithReleaseAtomic :one
WITH commit_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'commit', $2,
        0, (0::bigint - $2)::bigint, $2,
        $3, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
release_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'release', $10,
        $10, (0::bigint - $10)::bigint, 0,
        $11, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET available      = available + $10,
        reserved       = reserved - $12,
        used_total     = used_total + $2,
        last_ledger_id = (SELECT id FROM release_entry),
        version        = version + 1,
        updated_at     = NOW()
    WHERE business_account_id = $1
      AND version             = $13
      AND reserved            >= $12
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM commit_entry)          AS commit_ledger_id,
    (SELECT created_at FROM commit_entry)  AS commit_created_at,
    (SELECT id FROM release_entry)         AS release_ledger_id,
    (SELECT created_at FROM release_entry) AS release_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type CommitWithReleaseAtomicParams struct {
	BusinessAccountID    string      `json:"business_account_id"`
	ActualCost           int64       `json:"actual_cost"`
	CorrelationID        string      `json:"correlation_id"`
	Snapshot             []byte      `json:"snapshot"`
	ReferenceType        pgtype.Text `json:"reference_type"`
	ReferenceID          pgtype.Text `json:"reference_id"`
	Metadata             []byte      `json:"metadata"`
	ActorType            ActorType   `json:"actor_type"`
	ActorID              string      `json:"actor_id"`
	ReleaseAmount        int64       `json:"release_amount"`
	ReleaseCorrelationID string      `json:"release_correlation_id"`
	ReserveAmount        int64       `json:"reserve_amount"`
	ExpectedVersion      int64       `json:"expected_version"`
}

type CommitWithReleaseAtomicRow struct {
	CommitLedgerID    int64        `json:"commit_ledger_id"`
	CommitCreatedAt   time.Time    `json:"commit_created_at"`
	ReleaseLedgerID   int64        `json:"release_ledger_id"`
	ReleaseCreatedAt  time.Time    `json:"release_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// 结算（含部分释放残余）：actualCost < reserveAmount 时用本 query。
// 一次性 INSERT commit + release 两条 entry + UPDATE balance。
// CAS：不查 frozen；含 reserved >= @reserve_amount AND version=?
//
// 参数：
//
//	@reserve_amount, @actual_cost, @release_amount = reserve_amount - actual_cost
//	@release_correlation_id = correlation_id + ":release"
//
// 返回 commit + release 两条 ledger 信息 + 新 balance。
func (q *Queries) CommitWithReleaseAtomic(ctx context.Context, arg CommitWithReleaseAtomicParams) (CommitWithReleaseAtomicRow, error) {
	row := q.db.QueryRow(ctx, commitWithReleaseAtomic,
		arg.BusinessAccountID,
		arg.ActualCost,
		arg.CorrelationID,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ReleaseAmount,
		arg.ReleaseCorrelationID,
		arg.ReserveAmount,
		arg.ExpectedVersion,
	)
	var i CommitWithReleaseAtomicRow
	err := row.Scan(
		&i.CommitLedgerID,
		&i.CommitCreatedAt,
		&i.ReleaseLedgerID,
		&i.ReleaseCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const findActiveReserveByCorrelation = `-- name: FindActiveReserveByCorrelation :one
SELECT id, business_account_id, entry_type, amount,
       available_delta, reserved_delta, used_delta,
       correlation_id, idempotency_key, snapshot,
       reference_type, reference_id, metadata,
       actor_type, actor_id, canonical_body_sha256, created_at
FROM business_account_ledger l
WHERE l.business_account_id = $1
  AND l.correlation_id      = $2
  AND l.entry_type          = 'reserve'
  AND NOT EXISTS (
      SELECT 1 FROM business_account_ledger s
      WHERE s.business_account_id = l.business_account_id
        AND s.correlation_id      = l.correlation_id
        AND s.entry_type IN ('commit', 'release')
  )
`

type FindActiveReserveByCorrelationParams struct {
	BusinessAccountID string `json:"business_account_id"`
	CorrelationID     string `json:"correlation_id"`
}

type FindActiveReserveByCorrelationRow struct {
	ID                  int64           `json:"id"`
	BusinessAccountID   string          `json:"business_account_id"`
	EntryType           LedgerEntryType `json:"entry_type"`
	Amount              int64           `json:"amount"`
	AvailableDelta      int64           `json:"available_delta"`
	ReservedDelta       int64           `json:"reserved_delta"`
	UsedDelta           int64           `json:"used_delta"`
	CorrelationID       string          `json:"correlation_id"`
	IdempotencyKey      pgtype.Text     `json:"idempotency_key"`
	Snapshot            []byte          `json:"snapshot"`
	ReferenceType       pgtype.Text     `json:"reference_type"`
	ReferenceID         pgtype.Text     `json:"reference_id"`
	Metadata            []byte          `json:"metadata"`
	ActorType           ActorType       `json:"actor_type"`
	ActorID             string          `json:"actor_id"`
	CanonicalBodySha256 []byte          `json:"canonical_body_sha256"`
	CreatedAt           time.Time       `json:"created_at"`
}

// Commit/Release 前置校验：找同 correlation_id 的 active reserve（未 commit / release）。
// NOT EXISTS 子查询确认同 correlation_id 没有 commit/release entry。
func (q *Queries) FindActiveReserveByCorrelation(ctx context.Context, arg FindActiveReserveByCorrelationParams) (FindActiveReserveByCorrelationRow, error) {
	row := q.db.QueryRow(ctx, findActiveReserveByCorrelation, arg.BusinessAccountID, arg.CorrelationID)
	var i FindActiveReserveByCorrelationRow
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.EntryType,
		&i.Amount,
		&i.AvailableDelta,
		&i.ReservedDelta,
		&i.UsedDelta,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Snapshot,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.CanonicalBodySha256,
		&i.CreatedAt,
	)
	return i, err
}

const findAnyReserveByCorrelation = `-- name: FindAnyReserveByCorrelation :one
SELECT id, business_account_id, entry_type, amount,
       available_delta, reserved_delta, used_delta,
       correlation_id, idempotency_key, snapshot,
       reference_type, reference_id, metadata,
       actor_type, actor_id, canonical_body_sha256, created_at
FROM business_account_ledger
WHERE business_account_id = $1
  AND correlation_id      = $2
  AND entry_type          = 'reserve'
`

type FindAnyReserveByCorrelationParams struct {
	BusinessAccountID string `json:"business_account_id"`
	CorrelationID     string `json:"correlation_id"`
}

type FindAnyReserveByCorrelationRow struct {
	ID                  int64           `json:"id"`
	BusinessAccountID   string          `json:"business_account_id"`
	EntryType           LedgerEntryType `json:"entry_type"`
	Amount              int64           `json:"amount"`
	AvailableDelta      int64           `json:"available_delta"`
	ReservedDelta       int64           `json:"reserved_delta"`
	UsedDelta           int64           `json:"used_delta"`
	CorrelationID       string          `json:"correlation_id"`
	IdempotencyKey      pgtype.Text     `json:"idempotency_key"`
	Snapshot            []byte          `json:"snapshot"`
	ReferenceType       pgtype.Text     `json:"reference_type"`
	ReferenceID         pgtype.Text     `json:"reference_id"`
	Metadata            []byte          `json:"metadata"`
	ActorType           ActorType       `json:"actor_type"`
	ActorID             string          `json:"actor_id"`
	CanonicalBodySha256 []byte          `json:"canonical_body_sha256"`
	CreatedAt           time.Time       `json:"created_at"`
}

// 用于区分「未找到 reserve」与「reserve 已 commit/release」（service 用以返回不同 sentinel）。
func (q *Queries) FindAnyReserveByCorrelation(ctx context.Context, arg FindAnyReserveByCorrelationParams) (FindAnyReserveByCorrelationRow, error) {
	row := q.db.QueryRow(ctx, findAnyReserveByCorrelation, arg.BusinessAccountID, arg.CorrelationID)
	var i FindAnyReserveByCorrelationRow
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.EntryType,
		&i.Amount,
		&i.AvailableDelta,
		&i.ReservedDelta,
		&i.UsedDelta,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Snapshot,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.CanonicalBodySha256,
		&i.CreatedAt,
	)
	return i, err
}

const findLedgerEntryByCorrelationAndType = `-- name: FindLedgerEntryByCorrelationAndType :one
SELECT id, business_account_id, entry_type, amount,
       available_delta, reserved_delta, used_delta,
       correlation_id, idempotency_key, snapshot,
       reference_type, reference_id, metadata,
       actor_type, actor_id, canonical_body_sha256, created_at
FROM business_account_ledger
WHERE business_account_id = $1
  AND correlation_id      = $2
  AND entry_type          = $3
`

type FindLedgerEntryByCorrelationAndTypeParams struct {
	BusinessAccountID string          `json:"business_account_id"`
	CorrelationID     string          `json:"correlation_id"`
	EntryType         LedgerEntryType `json:"entry_type"`
}

type FindLedgerEntryByCorrelationAndTypeRow struct {
	ID                  int64           `json:"id"`
	BusinessAccountID   string          `json:"business_account_id"`
	EntryType           LedgerEntryType `json:"entry_type"`
	Amount              int64           `json:"amount"`
	AvailableDelta      int64           `json:"available_delta"`
	ReservedDelta       int64           `json:"reserved_delta"`
	UsedDelta           int64           `json:"used_delta"`
	CorrelationID       string          `json:"correlation_id"`
	IdempotencyKey      pgtype.Text     `json:"idempotency_key"`
	Snapshot            []byte          `json:"snapshot"`
	ReferenceType       pgtype.Text     `json:"reference_type"`
	ReferenceID         pgtype.Text     `json:"reference_id"`
	Metadata            []byte          `json:"metadata"`
	ActorType           ActorType       `json:"actor_type"`
	ActorID             string          `json:"actor_id"`
	CanonicalBodySha256 []byte          `json:"canonical_body_sha256"`
	CreatedAt           time.Time       `json:"created_at"`
}

// 通用反查：Reserve/Commit/Release/Refund 幂等用此 query 检查同 correlation_id+entry_type 是否已存在。
func (q *Queries) FindLedgerEntryByCorrelationAndType(ctx context.Context, arg FindLedgerEntryByCorrelationAndTypeParams) (FindLedgerEntryByCorrelationAndTypeRow, error) {
	row := q.db.QueryRow(ctx, findLedgerEntryByCorrelationAndType, arg.BusinessAccountID, arg.CorrelationID, arg.EntryType)
	var i FindLedgerEntryByCorrelationAndTypeRow
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.EntryType,
		&i.Amount,
		&i.AvailableDelta,
		&i.ReservedDelta,
		&i.UsedDelta,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Snapshot,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.CanonicalBodySha256,
		&i.CreatedAt,
	)
	return i, err
}

const findLedgerEntryByIdempotencyKey = `-- name: FindLedgerEntryByIdempotencyKey :one


SELECT id, business_account_id, entry_type, amount,
       available_delta, reserved_delta, used_delta,
       correlation_id, idempotency_key, snapshot,
       reference_type, reference_id, metadata,
       actor_type, actor_id, canonical_body_sha256, created_at
FROM business_account_ledger
WHERE entry_type      = $1
  AND idempotency_key = $2
`

type FindLedgerEntryByIdempotencyKeyParams struct {
	EntryType      LedgerEntryType `json:"entry_type"`
	IdempotencyKey pgtype.Text     `json:"idempotency_key"`
}

type FindLedgerEntryByIdempotencyKeyRow struct {
	ID                  int64           `json:"id"`
	BusinessAccountID   string          `json:"business_account_id"`
	EntryType           LedgerEntryType `json:"entry_type"`
	Amount              int64           `json:"amount"`
	AvailableDelta      int64           `json:"available_delta"`
	ReservedDelta       int64           `json:"reserved_delta"`
	UsedDelta           int64           `json:"used_delta"`
	CorrelationID       string          `json:"correlation_id"`
	IdempotencyKey      pgtype.Text     `json:"idempotency_key"`
	Snapshot            []byte          `json:"snapshot"`
	ReferenceType       pgtype.Text     `json:"reference_type"`
	ReferenceID         pgtype.Text     `json:"reference_id"`
	Metadata            []byte          `json:"metadata"`
	ActorType           ActorType       `json:"actor_type"`
	ActorID             string          `json:"actor_id"`
	CanonicalBodySha256 []byte          `json:"canonical_body_sha256"`
	CreatedAt           time.Time       `json:"created_at"`
}

// ============================================================================
// 2. 幂等查询
// ============================================================================
// 充值幂等命中查询：service 命中后比对 canonical_body_sha256，相同返原 entry，不同 ErrIdempotencyConflict。
func (q *Queries) FindLedgerEntryByIdempotencyKey(ctx context.Context, arg FindLedgerEntryByIdempotencyKeyParams) (FindLedgerEntryByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, findLedgerEntryByIdempotencyKey, arg.EntryType, arg.IdempotencyKey)
	var i FindLedgerEntryByIdempotencyKeyRow
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.EntryType,
		&i.Amount,
		&i.AvailableDelta,
		&i.ReservedDelta,
		&i.UsedDelta,
		&i.CorrelationID,
		&i.IdempotencyKey,
		&i.Snapshot,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.Metadata,
		&i.ActorType,
		&i.ActorID,
		&i.CanonicalBodySha256,
		&i.CreatedAt,
	)
	return i, err
}

const freezeAtomic = `-- name: FreezeAtomic :one
UPDATE business_account_balance
SET frozen        = true,
    frozen_reason = $1,
    frozen_at     = NOW(),
    version       = version + 1,
    updated_at    = NOW()
WHERE business_account_id = $2
  AND version             = $3
  AND frozen              = false
RETURNING business_account_id, available, reserved, used_total, recharge_total,
          refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
`

type FreezeAtomicParams struct {
	FrozenReason      pgtype.Text `json:"frozen_reason"`
	BusinessAccountID string      `json:"business_account_id"`
	ExpectedVersion   int64       `json:"expected_version"`
}

// 冻结账户余额：CAS 含 frozen=false AND version=?
// 已 frozen 返回 0 行；service 判幂等成功（不视为错误）。
// 不写 ledger entry（frozen 是 balance 字段，不涉及金额流水）；调用方自行写 outbox。
func (q *Queries) FreezeAtomic(ctx context.Context, arg FreezeAtomicParams) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, freezeAtomic, arg.FrozenReason, arg.BusinessAccountID, arg.ExpectedVersion)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const getLedgerEntriesForRebuild = `-- name: GetLedgerEntriesForRebuild :many


SELECT id, business_account_id, entry_type, amount,
       available_delta, reserved_delta, used_delta,
       correlation_id, idempotency_key, snapshot,
       reference_type, reference_id, metadata,
       actor_type, actor_id, canonical_body_sha256, created_at
FROM business_account_ledger
WHERE business_account_id = $1
ORDER BY id ASC
`

type GetLedgerEntriesForRebuildRow struct {
	ID                  int64           `json:"id"`
	BusinessAccountID   string          `json:"business_account_id"`
	EntryType           LedgerEntryType `json:"entry_type"`
	Amount              int64           `json:"amount"`
	AvailableDelta      int64           `json:"available_delta"`
	ReservedDelta       int64           `json:"reserved_delta"`
	UsedDelta           int64           `json:"used_delta"`
	CorrelationID       string          `json:"correlation_id"`
	IdempotencyKey      pgtype.Text     `json:"idempotency_key"`
	Snapshot            []byte          `json:"snapshot"`
	ReferenceType       pgtype.Text     `json:"reference_type"`
	ReferenceID         pgtype.Text     `json:"reference_id"`
	Metadata            []byte          `json:"metadata"`
	ActorType           ActorType       `json:"actor_type"`
	ActorID             string          `json:"actor_id"`
	CanonicalBodySha256 []byte          `json:"canonical_body_sha256"`
	CreatedAt           time.Time       `json:"created_at"`
}

// ============================================================================
// 4. rebuild 全量读
// ============================================================================
// rebuild TX2 用：按 id ASC 全量取 ledger，应用层累加得 expected balance。
// ORDER BY id 保证回放顺序与原写入顺序一致（虽然累加是可交换的，方便审计）。
func (q *Queries) GetLedgerEntriesForRebuild(ctx context.Context, businessAccountID string) ([]GetLedgerEntriesForRebuildRow, error) {
	rows, err := q.db.Query(ctx, getLedgerEntriesForRebuild, businessAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetLedgerEntriesForRebuildRow{}
	for rows.Next() {
		var i GetLedgerEntriesForRebuildRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.EntryType,
			&i.Amount,
			&i.AvailableDelta,
			&i.ReservedDelta,
			&i.UsedDelta,
			&i.CorrelationID,
			&i.IdempotencyKey,
			&i.Snapshot,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.Metadata,
			&i.ActorType,
			&i.ActorID,
			&i.CanonicalBodySha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rechargeAtomic = `-- name: RechargeAtomic :one




WITH new_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, idempotency_key, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id, canonical_body_sha256
    )
    VALUES (
        $1, 'recharge', $2,
        $2, 0, 0,
        $3, $4::text, $5,
        $6::text, $7::text, $8,
        $9, $10, $11::bytea
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET available      = available + $2,
        recharge_total = recharge_total + $2,
        last_ledger_id = (SELECT id FROM new_entry),
        version        = version + 1,
        updated_at     = NOW()
    WHERE business_account_id = $1
      AND version             = $12
      AND frozen              = false
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM new_entry)                AS new_ledger_id,
    (SELECT created_at FROM new_entry)        AS new_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type RechargeAtomicParams struct {
	BusinessAccountID   string      `json:"business_account_id"`
	Amount              int64       `json:"amount"`
	CorrelationID       string      `json:"correlation_id"`
	IdempotencyKey      pgtype.Text `json:"idempotency_key"`
	Snapshot            []byte      `json:"snapshot"`
	ReferenceType       pgtype.Text `json:"reference_type"`
	ReferenceID         pgtype.Text `json:"reference_id"`
	Metadata            []byte      `json:"metadata"`
	ActorType           ActorType   `json:"actor_type"`
	ActorID             string      `json:"actor_id"`
	CanonicalBodySha256 []byte      `json:"canonical_body_sha256"`
	ExpectedVersion     int64       `json:"expected_version"`
}

type RechargeAtomicRow struct {
	NewLedgerID       int64        `json:"new_ledger_id"`
	NewCreatedAt      time.Time    `json:"new_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// ledger.sql —— 账本流水写入 + 幂等查询 + drift 聚合 + rebuild 全量读
//
// 设计文档：docs/multimedia-gateway-design.md §3ter
// 实施计划：docs/plans/2026-05-26-002-...-plan.md Unit 2
//
// 写操作统一走 PG CTE 单语句模式：
//
//	WITH new_entry AS (INSERT INTO business_account_ledger ... RETURNING ...)
//	UPDATE business_account_balance SET ... WHERE CAS 条件 RETURNING ...
//
// 关键 PG 语义（务必牢记）：
//
//	data-modifying CTE 即使最终 SELECT 0 行，sibling INSERT 仍**执行到完成**。
//	原子性靠 tx 级 ROLLBACK 保证 —— service 在 pgx.ErrNoRows 时**必须**显式 tx.Rollback。
//
// sqlc 命名参数注意：
//
//	sqlc v1.30.0 对 `-@param`（紧贴一元负号）解析有 bug，会把 `@param` 留在生成 SQL 中。
//	解决：所有负值表达式写成 `(0 - @param)::bigint`，sqlc 能正确替换为 `(0 - $N)::bigint`。
//
// CAS 字段策略：
//   - Recharge / Reserve   含 frozen = false（拒绝冻结账户的新入金 / 预占）
//   - Commit / Release / Refund / Freeze / Unfreeze   不查 frozen（允许 inflight 完成 + 管理动作）
//   - 所有写都含 version = @expected_version 防丢失更新
//
// ============================================================================
// 1. 写操作：CTE 单语句（INSERT ledger + UPDATE balance）
// ============================================================================
// 充值：available 增 + recharge_total 增；CAS WHERE frozen=false AND version=?
// 0 行 = CAS 失败（frozen / version 冲突）；service 同 tx 内 fresh-read 判错。
func (q *Queries) RechargeAtomic(ctx context.Context, arg RechargeAtomicParams) (RechargeAtomicRow, error) {
	row := q.db.QueryRow(ctx, rechargeAtomic,
		arg.BusinessAccountID,
		arg.Amount,
		arg.CorrelationID,
		arg.IdempotencyKey,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.CanonicalBodySha256,
		arg.ExpectedVersion,
	)
	var i RechargeAtomicRow
	err := row.Scan(
		&i.NewLedgerID,
		&i.NewCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const refundAtomic = `-- name: RefundAtomic :one
WITH new_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'refund', $2,
        $2, 0, (0::bigint - $2)::bigint,
        $3, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET available    = available + $2,
        used_total   = used_total - $2,
        refund_total = refund_total + $2,
        last_ledger_id = (SELECT id FROM new_entry),
        version      = version + 1,
        updated_at   = NOW()
    WHERE business_account_id = $1
      AND version             = $10
      AND used_total          >= $2
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM new_entry)                AS new_ledger_id,
    (SELECT created_at FROM new_entry)        AS new_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type RefundAtomicParams struct {
	BusinessAccountID string      `json:"business_account_id"`
	Amount            int64       `json:"amount"`
	CorrelationID     string      `json:"correlation_id"`
	Snapshot          []byte      `json:"snapshot"`
	ReferenceType     pgtype.Text `json:"reference_type"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	Metadata          []byte      `json:"metadata"`
	ActorType         ActorType   `json:"actor_type"`
	ActorID           string      `json:"actor_id"`
	ExpectedVersion   int64       `json:"expected_version"`
}

type RefundAtomicRow struct {
	NewLedgerID       int64        `json:"new_ledger_id"`
	NewCreatedAt      time.Time    `json:"new_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// 退款：used_total 减 + available 增 + refund_total 增；CAS 含 used_total >= @amount AND version=?
// 不查 frozen（管理动作允许）。refund_total 不进不变量等式，单独自增。
func (q *Queries) RefundAtomic(ctx context.Context, arg RefundAtomicParams) (RefundAtomicRow, error) {
	row := q.db.QueryRow(ctx, refundAtomic,
		arg.BusinessAccountID,
		arg.Amount,
		arg.CorrelationID,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ExpectedVersion,
	)
	var i RefundAtomicRow
	err := row.Scan(
		&i.NewLedgerID,
		&i.NewCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const releaseAtomic = `-- name: ReleaseAtomic :one
WITH new_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'release', $2,
        $2, (0::bigint - $2)::bigint, 0,
        $3, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET available  = available + $2,
        reserved   = reserved - $2,
        last_ledger_id = (SELECT id FROM new_entry),
        version    = version + 1,
        updated_at = NOW()
    WHERE business_account_id = $1
      AND version             = $10
      AND reserved            >= $2
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM new_entry)                AS new_ledger_id,
    (SELECT created_at FROM new_entry)        AS new_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type ReleaseAtomicParams struct {
	BusinessAccountID string      `json:"business_account_id"`
	Amount            int64       `json:"amount"`
	CorrelationID     string      `json:"correlation_id"`
	Snapshot          []byte      `json:"snapshot"`
	ReferenceType     pgtype.Text `json:"reference_type"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	Metadata          []byte      `json:"metadata"`
	ActorType         ActorType   `json:"actor_type"`
	ActorID           string      `json:"actor_id"`
	ExpectedVersion   int64       `json:"expected_version"`
}

type ReleaseAtomicRow struct {
	NewLedgerID       int64        `json:"new_ledger_id"`
	NewCreatedAt      time.Time    `json:"new_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// 释放预占：reserved 减 + available 增；CAS 含 reserved >= @amount AND version=?
// 不查 frozen（允许 inflight 完成）。
func (q *Queries) ReleaseAtomic(ctx context.Context, arg ReleaseAtomicParams) (ReleaseAtomicRow, error) {
	row := q.db.QueryRow(ctx, releaseAtomic,
		arg.BusinessAccountID,
		arg.Amount,
		arg.CorrelationID,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ExpectedVersion,
	)
	var i ReleaseAtomicRow
	err := row.Scan(
		&i.NewLedgerID,
		&i.NewCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const reserveAtomic = `-- name: ReserveAtomic :one
WITH new_entry AS (
    INSERT INTO business_account_ledger (
        business_account_id, entry_type, amount,
        available_delta, reserved_delta, used_delta,
        correlation_id, snapshot,
        reference_type, reference_id, metadata,
        actor_type, actor_id
    )
    VALUES (
        $1, 'reserve', $2,
        (0::bigint - $2)::bigint, $2, 0,
        $3, $4,
        $5::text, $6::text, $7,
        $8, $9
    )
    RETURNING id, created_at
),
updated_balance AS (
    UPDATE business_account_balance
    SET available  = available - $2,
        reserved   = reserved + $2,
        last_ledger_id = (SELECT id FROM new_entry),
        version    = version + 1,
        updated_at = NOW()
    WHERE business_account_id = $1
      AND version             = $10
      AND frozen              = false
      AND available           >= $2
    RETURNING business_account_id, available, reserved, used_total, recharge_total,
              refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
)
SELECT
    (SELECT id FROM new_entry)                AS new_ledger_id,
    (SELECT created_at FROM new_entry)        AS new_created_at,
    ub.business_account_id,
    ub.available,
    ub.reserved,
    ub.used_total,
    ub.recharge_total,
    ub.refund_total,
    ub.version,
    ub.frozen,
    ub.frozen_reason,
    ub.frozen_at,
    ub.updated_at,
    ub.last_ledger_id
FROM updated_balance ub
`

type ReserveAtomicParams struct {
	BusinessAccountID string      `json:"business_account_id"`
	Amount            int64       `json:"amount"`
	CorrelationID     string      `json:"correlation_id"`
	Snapshot          []byte      `json:"snapshot"`
	ReferenceType     pgtype.Text `json:"reference_type"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	Metadata          []byte      `json:"metadata"`
	ActorType         ActorType   `json:"actor_type"`
	ActorID           string      `json:"actor_id"`
	ExpectedVersion   int64       `json:"expected_version"`
}

type ReserveAtomicRow struct {
	NewLedgerID       int64        `json:"new_ledger_id"`
	NewCreatedAt      time.Time    `json:"new_created_at"`
	BusinessAccountID string       `json:"business_account_id"`
	Available         int64        `json:"available"`
	Reserved          int64        `json:"reserved"`
	UsedTotal         int64        `json:"used_total"`
	RechargeTotal     int64        `json:"recharge_total"`
	RefundTotal       int64        `json:"refund_total"`
	Version           int64        `json:"version"`
	Frozen            bool         `json:"frozen"`
	FrozenReason      pgtype.Text  `json:"frozen_reason"`
	FrozenAt          sql.NullTime `json:"frozen_at"`
	UpdatedAt         time.Time    `json:"updated_at"`
	LastLedgerID      int64        `json:"last_ledger_id"`
}

// 预占：available 减 + reserved 增；CAS 含 available >= @amount AND frozen=false AND version=?
// available_delta 用 (0::bigint - @amount)::bigint 表达负值（sqlc 解析必须）。
func (q *Queries) ReserveAtomic(ctx context.Context, arg ReserveAtomicParams) (ReserveAtomicRow, error) {
	row := q.db.QueryRow(ctx, reserveAtomic,
		arg.BusinessAccountID,
		arg.Amount,
		arg.CorrelationID,
		arg.Snapshot,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.Metadata,
		arg.ActorType,
		arg.ActorID,
		arg.ExpectedVersion,
	)
	var i ReserveAtomicRow
	err := row.Scan(
		&i.NewLedgerID,
		&i.NewCreatedAt,
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}

const sumLedgerDeltasByAccount = `-- name: SumLedgerDeltasByAccount :one


SELECT
    COALESCE(SUM(available_delta), 0)::bigint AS available_sum,
    COALESCE(SUM(reserved_delta),  0)::bigint AS reserved_sum,
    COALESCE(SUM(used_delta),      0)::bigint AS used_sum,
    COALESCE(SUM(amount) FILTER (WHERE entry_type = 'recharge'), 0)::bigint AS recharge_sum,
    COALESCE(SUM(amount) FILTER (WHERE entry_type = 'refund'),   0)::bigint AS refund_sum,
    COALESCE(MAX(id), 0)::bigint AS max_ledger_id
FROM business_account_ledger
WHERE business_account_id = $1
`

type SumLedgerDeltasByAccountRow struct {
	AvailableSum int64 `json:"available_sum"`
	ReservedSum  int64 `json:"reserved_sum"`
	UsedSum      int64 `json:"used_sum"`
	RechargeSum  int64 `json:"recharge_sum"`
	RefundSum    int64 `json:"refund_sum"`
	MaxLedgerID  int64 `json:"max_ledger_id"`
}

// ============================================================================
// 3. drift reconciler 聚合
// ============================================================================
// reconciler 用：对单个账户的全部 ledger entry SUM 各 delta，
// 与 balance 表比对得 drift。recharge_sum / refund_sum 用 FILTER 仅累加对应 entry_type。
// COALESCE 兜底 NULL（账户 0 条 ledger 时 SUM 返回 NULL）。
func (q *Queries) SumLedgerDeltasByAccount(ctx context.Context, businessAccountID string) (SumLedgerDeltasByAccountRow, error) {
	row := q.db.QueryRow(ctx, sumLedgerDeltasByAccount, businessAccountID)
	var i SumLedgerDeltasByAccountRow
	err := row.Scan(
		&i.AvailableSum,
		&i.ReservedSum,
		&i.UsedSum,
		&i.RechargeSum,
		&i.RefundSum,
		&i.MaxLedgerID,
	)
	return i, err
}

const unfreezeAtomic = `-- name: UnfreezeAtomic :one
UPDATE business_account_balance
SET frozen        = false,
    frozen_reason = $1,
    frozen_at     = NULL,
    version       = version + 1,
    updated_at    = NOW()
WHERE business_account_id = $2
  AND version             = $3
  AND frozen              = true
RETURNING business_account_id, available, reserved, used_total, recharge_total,
          refund_total, version, frozen, frozen_reason, frozen_at, updated_at, last_ledger_id
`

type UnfreezeAtomicParams struct {
	FrozenReason      pgtype.Text `json:"frozen_reason"`
	BusinessAccountID string      `json:"business_account_id"`
	ExpectedVersion   int64       `json:"expected_version"`
}

// 解冻：CAS 含 frozen=true AND version=?；frozen_reason 重写为新值（rebuild_completed / manual_unfreeze）。
// 0 行 = 已 unfrozen（幂等成功）或 version 冲突。
func (q *Queries) UnfreezeAtomic(ctx context.Context, arg UnfreezeAtomicParams) (BusinessAccountBalance, error) {
	row := q.db.QueryRow(ctx, unfreezeAtomic, arg.FrozenReason, arg.BusinessAccountID, arg.ExpectedVersion)
	var i BusinessAccountBalance
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Available,
		&i.Reserved,
		&i.UsedTotal,
		&i.RechargeTotal,
		&i.RefundTotal,
		&i.Version,
		&i.Frozen,
		&i.FrozenReason,
		&i.FrozenAt,
		&i.UpdatedAt,
		&i.LastLedgerID,
	)
	return i, err
}
