// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type BusinessAccountStatus string

const (
	BusinessAccountStatusActive    BusinessAccountStatus = "active"
	BusinessAccountStatusSuspended BusinessAccountStatus = "suspended"
	BusinessAccountStatusFrozen    BusinessAccountStatus = "frozen"
	BusinessAccountStatusDeleted   BusinessAccountStatus = "deleted"
)

func (e *BusinessAccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BusinessAccountStatus(s)
	case string:
		*e = BusinessAccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BusinessAccountStatus: %T", src)
	}
	return nil
}

type NullBusinessAccountStatus struct {
	BusinessAccountStatus BusinessAccountStatus `json:"business_account_status"`
	Valid                 bool                  `json:"valid"` // Valid is true if BusinessAccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBusinessAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BusinessAccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BusinessAccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBusinessAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BusinessAccountStatus), nil
}

type FallbackPolicy string

const (
	FallbackPolicyStrict            FallbackPolicy = "strict"
	FallbackPolicyNextRule          FallbackPolicy = "next_rule"
	FallbackPolicyGlobalPool        FallbackPolicy = "global_pool"
	FallbackPolicyLegacyDistributor FallbackPolicy = "legacy_distributor"
)

func (e *FallbackPolicy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FallbackPolicy(s)
	case string:
		*e = FallbackPolicy(s)
	default:
		return fmt.Errorf("unsupported scan type for FallbackPolicy: %T", src)
	}
	return nil
}

type NullFallbackPolicy struct {
	FallbackPolicy FallbackPolicy `json:"fallback_policy"`
	Valid          bool           `json:"valid"` // Valid is true if FallbackPolicy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFallbackPolicy) Scan(value interface{}) error {
	if value == nil {
		ns.FallbackPolicy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FallbackPolicy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFallbackPolicy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FallbackPolicy), nil
}

type LedgerEntryType string

const (
	LedgerEntryTypeRecharge         LedgerEntryType = "recharge"
	LedgerEntryTypeReserve          LedgerEntryType = "reserve"
	LedgerEntryTypeCommit           LedgerEntryType = "commit"
	LedgerEntryTypeRelease          LedgerEntryType = "release"
	LedgerEntryTypeRefund           LedgerEntryType = "refund"
	LedgerEntryTypeCashout          LedgerEntryType = "cashout"
	LedgerEntryTypeRechargeReversal LedgerEntryType = "recharge_reversal"
	LedgerEntryTypeAdjust           LedgerEntryType = "adjust"
	LedgerEntryTypeExpire           LedgerEntryType = "expire"
)

func (e *LedgerEntryType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LedgerEntryType(s)
	case string:
		*e = LedgerEntryType(s)
	default:
		return fmt.Errorf("unsupported scan type for LedgerEntryType: %T", src)
	}
	return nil
}

type NullLedgerEntryType struct {
	LedgerEntryType LedgerEntryType `json:"ledger_entry_type"`
	Valid           bool            `json:"valid"` // Valid is true if LedgerEntryType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLedgerEntryType) Scan(value interface{}) error {
	if value == nil {
		ns.LedgerEntryType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LedgerEntryType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLedgerEntryType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LedgerEntryType), nil
}

type OutboxDeliveryStatus string

const (
	OutboxDeliveryStatusPending    OutboxDeliveryStatus = "pending"
	OutboxDeliveryStatusDelivering OutboxDeliveryStatus = "delivering"
	OutboxDeliveryStatusDelivered  OutboxDeliveryStatus = "delivered"
	OutboxDeliveryStatusFailed     OutboxDeliveryStatus = "failed"
	OutboxDeliveryStatusDeadLetter OutboxDeliveryStatus = "dead_letter"
)

func (e *OutboxDeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OutboxDeliveryStatus(s)
	case string:
		*e = OutboxDeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OutboxDeliveryStatus: %T", src)
	}
	return nil
}

type NullOutboxDeliveryStatus struct {
	OutboxDeliveryStatus OutboxDeliveryStatus `json:"outbox_delivery_status"`
	Valid                bool                 `json:"valid"` // Valid is true if OutboxDeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOutboxDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OutboxDeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OutboxDeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOutboxDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OutboxDeliveryStatus), nil
}

type TaskStatus string

const (
	TaskStatusSUBMITTED          TaskStatus = "SUBMITTED"
	TaskStatusUPSTREAMSUBMITTING TaskStatus = "UPSTREAM_SUBMITTING"
	TaskStatusUPSTREAMSUBMITTED  TaskStatus = "UPSTREAM_SUBMITTED"
	TaskStatusCOMPLETED          TaskStatus = "COMPLETED"
	TaskStatusFAILED             TaskStatus = "FAILED"
	TaskStatusCANCELLED          TaskStatus = "CANCELLED"
	TaskStatusEXPIRED            TaskStatus = "EXPIRED"
	TaskStatusSETTLING           TaskStatus = "SETTLING"
	TaskStatusSETTLED            TaskStatus = "SETTLED"
)

func (e *TaskStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TaskStatus(s)
	case string:
		*e = TaskStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TaskStatus: %T", src)
	}
	return nil
}

type NullTaskStatus struct {
	TaskStatus TaskStatus `json:"task_status"`
	Valid      bool       `json:"valid"` // Valid is true if TaskStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTaskStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TaskStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TaskStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTaskStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TaskStatus), nil
}

// 业务账户：业务系统侧企业账户在网关侧的镜像（CONTEXT.md business_account）
type BusinessAccount struct {
	ID     string                `json:"id"`
	Status BusinessAccountStatus `json:"status"`
	// 企业隔离硬开关；true 时禁止跨企业降级（见 8.3.6）
	IsolationRequired bool `json:"isolation_required"`
	// 紧急逃生门截止时间；NULL = 未启用
	BreakGlassUntil sql.NullTime `json:"break_glass_until"`
	Metadata        []byte       `json:"metadata"`
	CreatedAt       time.Time    `json:"created_at"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

// 账户余额投影：ledger 严格投影；drift 检测命中即冻结（CONTEXT.md balance）
type BusinessAccountBalance struct {
	BusinessAccountID string `json:"business_account_id"`
	Available         int64  `json:"available"`
	Reserved          int64  `json:"reserved"`
	UsedTotal         int64  `json:"used_total"`
	RechargeTotal     int64  `json:"recharge_total"`
	// 累计退款（审计字段，不进入账本不变量）
	RefundTotal int64 `json:"refund_total"`
	// 乐观锁版本；CAS 更新 balance 时必须 SET version = version + 1
	Version      int64        `json:"version"`
	Frozen       bool         `json:"frozen"`
	FrozenReason pgtype.Text  `json:"frozen_reason"`
	FrozenAt     sql.NullTime `json:"frozen_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

// 账本不可变流水：所有扣减 / 退款 / 对账的唯一真相源（CONTEXT.md ledger）
type BusinessAccountLedger struct {
	ID                int64           `json:"id"`
	BusinessAccountID string          `json:"business_account_id"`
	EntryType         LedgerEntryType `json:"entry_type"`
	Amount            int64           `json:"amount"`
	// 关联同一笔业务流的多个 entry（reserve → commit / release）
	CorrelationID string `json:"correlation_id"`
	// 充值幂等键 sha256(external_ref + canonical_body)，部分唯一
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Snapshot       []byte      `json:"snapshot"`
	CreatedAt      time.Time   `json:"created_at"`
}

// 渠道：一组上游 provider 凭据的抽象（CONTEXT.md channel）
type Channel struct {
	ID           int64  `json:"id"`
	Name         string `json:"name"`
	ProviderType string `json:"provider_type"`
	Enabled      bool   `json:"enabled"`
	// 业务账户白名单；空数组 = 不限制，非空 = 仅列内账户可用
	RestrictedBusinessAccounts []string    `json:"restricted_business_accounts"`
	ChannelPurpose             pgtype.Text `json:"channel_purpose"`
	// envelope encryption 密文；明文绝不入库
	CredentialsEncrypted []byte `json:"credentials_encrypted"`
	// KEK 版本号，支持平滑轮换
	KeyVersion    int32     `json:"key_version"`
	OtherSettings []byte    `json:"other_settings"`
	CreatedAt     time.Time `json:"created_at"`
	UpdatedAt     time.Time `json:"updated_at"`
}

// 路由规则：将 (账户 + 请求参数) 映射到候选 channel（CONTEXT.md channel_routing_rule）
type ChannelRoutingRule struct {
	ID int64 `json:"id"`
	// NULL = 全局默认规则；非 NULL = 企业覆盖规则
	BusinessAccountID pgtype.Text `json:"business_account_id"`
	Priority          int32       `json:"priority"`
	ConditionExpr     string      `json:"condition_expr"`
	TargetChannelIds  []int64     `json:"target_channel_ids"`
	// 默认 strict（fail-closed）；isolation_required 企业禁用 global_pool / legacy_distributor
	FallbackPolicy FallbackPolicy `json:"fallback_policy"`
	Enabled        bool           `json:"enabled"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}

// Admin Token：业务系统调网关的认证凭据（CONTEXT.md Admin Token）
type GatewayAdminToken struct {
	ID int64 `json:"id"`
	// bcrypt/argon2id 哈希；明文绝不入库
	TokenHash   string `json:"token_hash"`
	Description string `json:"description"`
	// 细粒度权限范围；推荐生产环境只授权必要 scope
	Scopes []string `json:"scopes"`
	// CIDR 源 IP 白名单；未匹配请求直接 401，不消耗限流
	IpAllowlist []netip.Prefix `json:"ip_allowlist"`
	// NULL = 无限；非 NULL = 单日充值上限（阀门）
	DailyRechargeQuotaLimit pgtype.Int8  `json:"daily_recharge_quota_limit"`
	DailyAccountCreateLimit pgtype.Int4  `json:"daily_account_create_limit"`
	SingleRechargeMax       pgtype.Int8  `json:"single_recharge_max"`
	RequestsPerMinute       pgtype.Int4  `json:"requests_per_minute"`
	CircuitBreakerEnabled   bool         `json:"circuit_breaker_enabled"`
	CreatedBy               string       `json:"created_by"`
	CreatedAt               time.Time    `json:"created_at"`
	ExpiresAt               sql.NullTime `json:"expires_at"`
	RevokedAt               sql.NullTime `json:"revoked_at"`
}

// 异步任务：长耗时上游调用的本地记录（CONTEXT.md task）
type Task struct {
	ID                string      `json:"id"`
	BusinessAccountID string      `json:"business_account_id"`
	TokenID           pgtype.Int8 `json:"token_id"`
	ChannelID         pgtype.Int8 `json:"channel_id"`
	ProviderType      string      `json:"provider_type"`
	Model             string      `json:"model"`
	// 任务状态机；状态转移仅允许 §9ter.2 状态转移表方向（CAS）
	Status         TaskStatus  `json:"status"`
	UpstreamTaskID pgtype.Text `json:"upstream_task_id"`
	// v1.2.3：worker 抢占 lease 截止；超时 cron 回退到 SUBMITTED
	SubmitLockedUntil sql.NullTime `json:"submit_locked_until"`
	SubmitLockedBy    pgtype.Text  `json:"submit_locked_by"`
	// v1.2.3：UPSTREAM_SUBMITTING 崩溃恢复次数；>=3 转 FAILED
	SubmitRecoverCount int32 `json:"submit_recover_count"`
	// TaskFinancialSnapshot（AuthSnapshot + PricingSnapshot + ReservationLedgerID）
	FinancialSnapshot []byte `json:"financial_snapshot"`
	// 跨月归属：固定为提交时刻的 YYYY-MM，永不切分
	AccountingMonth string       `json:"accounting_month"`
	SubmittedAt     time.Time    `json:"submitted_at"`
	TerminalAt      sql.NullTime `json:"terminal_at"`
	ErrorCode       pgtype.Text  `json:"error_code"`
	ErrorMessage    pgtype.Text  `json:"error_message"`
	UpdatedAt       time.Time    `json:"updated_at"`
}

// 事件出箱：与 ledger 同事务写入，业务系统拉取/重放游标（CONTEXT.md outbox）
type WebhookEventOutbox struct {
	EventID           int64       `json:"event_id"`
	BusinessAccountID pgtype.Text `json:"business_account_id"`
	EventType         string      `json:"event_type"`
	Payload           []byte      `json:"payload"`
	// true = 财务事件（保留 ≥ 1 年）；false = 非财务（保留 ≥ 30 天）
	IsFinancial      bool                 `json:"is_financial"`
	RetentionUntil   time.Time            `json:"retention_until"`
	DeliveryStatus   OutboxDeliveryStatus `json:"delivery_status"`
	DeliveryAttempts int32                `json:"delivery_attempts"`
	// claim/lease：当前抢占该事件的 worker ID（hostname_pid）
	LockedBy pgtype.Text `json:"locked_by"`
	// lease 截止时间；NOW() > locked_until 时其他 worker 可抢占
	LockedUntil sql.NullTime `json:"locked_until"`
	// 业务侧去重键；财务事件长期去重 ≥ 1 年
	DeliveryIdempotencyKey string       `json:"delivery_idempotency_key"`
	LastPushedAt           sql.NullTime `json:"last_pushed_at"`
	CreatedAt              time.Time    `json:"created_at"`
}

// Webhook 订阅：业务账户对网关事件的回调注册
type WebhookSubscription struct {
	ID                int64  `json:"id"`
	BusinessAccountID string `json:"business_account_id"`
	EndpointUrl       string `json:"endpoint_url"`
	// HMAC 签名密钥密文；明文绝不入库
	HmacSecretEncrypted []byte `json:"hmac_secret_encrypted"`
	KeyVersion          int32  `json:"key_version"`
	// 订阅的事件类型；空数组 = 订阅全部
	EventTypes []string  `json:"event_types"`
	Enabled    bool      `json:"enabled"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}
