// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: operator_account.sql

package db

import (
	"context"
	"time"
)

const countOperatorAccounts = `-- name: CountOperatorAccounts :one
SELECT COUNT(*) AS total FROM operator_account
`

// 计数；初始管理员种子幂等判定（表空才种子）。
func (q *Queries) CountOperatorAccounts(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countOperatorAccounts)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getOperatorAccountByID = `-- name: GetOperatorAccountByID :one
SELECT id, username, enabled, created_by, created_at, updated_at
FROM operator_account
WHERE id = $1
`

type GetOperatorAccountByIDRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Enabled   bool      `json:"enabled"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// 按 id 查账户（**不含 password_hash**；运维 / 会话归属校验用）。
func (q *Queries) GetOperatorAccountByID(ctx context.Context, id int64) (GetOperatorAccountByIDRow, error) {
	row := q.db.QueryRow(ctx, getOperatorAccountByID, id)
	var i GetOperatorAccountByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOperatorAccountByUsername = `-- name: GetOperatorAccountByUsername :one
SELECT id, username, password_hash, enabled, created_by, created_at, updated_at
FROM operator_account
WHERE username = $1
`

// 认证热路径：按用户名取账户（**含 password_hash**，仅认证用）。
// 调用方校验 enabled 再比对口令（禁用账户拒登）。
func (q *Queries) GetOperatorAccountByUsername(ctx context.Context, username string) (OperatorAccount, error) {
	row := q.db.QueryRow(ctx, getOperatorAccountByUsername, username)
	var i OperatorAccount
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.PasswordHash,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOperatorAccount = `-- name: InsertOperatorAccount :one


INSERT INTO operator_account (username, password_hash, enabled, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, username, enabled, created_by, created_at, updated_at
`

type InsertOperatorAccountParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
	Enabled      bool   `json:"enabled"`
	CreatedBy    string `json:"created_by"`
}

type InsertOperatorAccountRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Enabled   bool      `json:"enabled"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// operator_account.sql —— 运维登录账户 CRUD + 认证热路径
//
// 决策依据：ADR-0008（管理后台会话认证）
// 实施计划：docs/plans/2026-05-31-001-feat-admin-console-config-plan.md Unit 2（供 Unit 3 operator service）
//
// 安全约定：
//   - password_hash 是 bcrypt(口令) hex；明文绝不入库。
//   - **仅** GetOperatorAccountByUsername 返回 password_hash（认证用）；List / 其余视图绝不回显哈希。
//   - 认证由 service 层（Unit 3）用 bcrypt.CompareHashAndPassword 完成；本层只取哈希。
//
// 创建运维账户；password_hash 由 service 层 bcrypt 后传入。
// created_by：初始管理员种子为 'seed'，后台开通为 'operator:<id>'。
// username 唯一冲突 → service 层判 ErrUsernameExists（SQLSTATE 23505）。
func (q *Queries) InsertOperatorAccount(ctx context.Context, arg InsertOperatorAccountParams) (InsertOperatorAccountRow, error) {
	row := q.db.QueryRow(ctx, insertOperatorAccount,
		arg.Username,
		arg.PasswordHash,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i InsertOperatorAccountRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOperatorAccounts = `-- name: ListOperatorAccounts :many
SELECT id, username, enabled, created_by, created_at, updated_at
FROM operator_account
ORDER BY created_at DESC
`

type ListOperatorAccountsRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Enabled   bool      `json:"enabled"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// 列出全部运维账户（**不含 password_hash**）；后台账户管理用。按 created_at DESC。
func (q *Queries) ListOperatorAccounts(ctx context.Context) ([]ListOperatorAccountsRow, error) {
	rows, err := q.db.Query(ctx, listOperatorAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOperatorAccountsRow{}
	for rows.Next() {
		var i ListOperatorAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setOperatorAccountEnabled = `-- name: SetOperatorAccountEnabled :one
UPDATE operator_account
SET enabled    = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, username, enabled, created_by, created_at, updated_at
`

type SetOperatorAccountEnabledParams struct {
	Enabled bool  `json:"enabled"`
	ID      int64 `json:"id"`
}

type SetOperatorAccountEnabledRow struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	Enabled   bool      `json:"enabled"`
	CreatedBy string    `json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

// 启用 / 禁用账户（禁用即时阻断后续登录；已建会话由禁用账户校验失效）。
// 不存在 id 返 0 rows → service 判 ErrNotFound。
func (q *Queries) SetOperatorAccountEnabled(ctx context.Context, arg SetOperatorAccountEnabledParams) (SetOperatorAccountEnabledRow, error) {
	row := q.db.QueryRow(ctx, setOperatorAccountEnabled, arg.Enabled, arg.ID)
	var i SetOperatorAccountEnabledRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOperatorPassword = `-- name: UpdateOperatorPassword :execrows
UPDATE operator_account
SET password_hash = $1,
    updated_at    = NOW()
WHERE id = $2
`

type UpdateOperatorPasswordParams struct {
	PasswordHash string `json:"password_hash"`
	ID           int64  `json:"id"`
}

// 改口令（password_hash 由 service bcrypt 后传入）；返回受影响行数判断是否存在。
func (q *Queries) UpdateOperatorPassword(ctx context.Context, arg UpdateOperatorPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOperatorPassword, arg.PasswordHash, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
