// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oss_object_meta.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const getOSSObjectMetaByTask = `-- name: GetOSSObjectMetaByTask :one
SELECT task_id, business_account_id, bucket, object_key, region, endpoint, content_type, size_bytes, stored_at FROM oss_object_meta WHERE task_id = $1
`

// 按 task_id 取产物元数据（store 幂等判存 + Unit 10 GET 现签 URL 用）。不命中返 0 rows。
func (q *Queries) GetOSSObjectMetaByTask(ctx context.Context, taskID string) (OssObjectMetum, error) {
	row := q.db.QueryRow(ctx, getOSSObjectMetaByTask, taskID)
	var i OssObjectMetum
	err := row.Scan(
		&i.TaskID,
		&i.BusinessAccountID,
		&i.Bucket,
		&i.ObjectKey,
		&i.Region,
		&i.Endpoint,
		&i.ContentType,
		&i.SizeBytes,
		&i.StoredAt,
	)
	return i, err
}

const insertOSSObjectMeta = `-- name: InsertOSSObjectMeta :execrows


INSERT INTO oss_object_meta (
    task_id, business_account_id, bucket, object_key, region, endpoint, content_type, size_bytes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
ON CONFLICT (task_id) DO NOTHING
`

type InsertOSSObjectMetaParams struct {
	TaskID            string `json:"task_id"`
	BusinessAccountID string `json:"business_account_id"`
	Bucket            string `json:"bucket"`
	ObjectKey         string `json:"object_key"`
	Region            string `json:"region"`
	Endpoint          string `json:"endpoint"`
	ContentType       string `json:"content_type"`
	SizeBytes         int64  `json:"size_bytes"`
}

// oss_object_meta.sql —— TOS 结果对象元数据 CRUD + 转存恢复扫描（Phase 2 Unit 9）
//
// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 9
// 决策：ADR-0006 决策 3（官方 TOS SDK；结果对象 + 受限签名 URL）
//
// 不存签名 URL / 上游源 URL（见 migration 0010 说明）；PK=task_id 天然幂等。
// 记录转存产物元数据；ON CONFLICT DO NOTHING 实现幂等（重复 store / 并发重投命中 PK 冲突 → 0 行）。
// 返回受影响行数：1 = 本次插入，0 = 已存在（幂等跳过）。
func (q *Queries) InsertOSSObjectMeta(ctx context.Context, arg InsertOSSObjectMetaParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertOSSObjectMeta,
		arg.TaskID,
		arg.BusinessAccountID,
		arg.Bucket,
		arg.ObjectKey,
		arg.Region,
		arg.Endpoint,
		arg.ContentType,
		arg.SizeBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scanSettledNeedingStore = `-- name: ScanSettledNeedingStore :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status = 'SETTLED'
  AND error_code IS NULL
  AND terminal_at >= $1
  AND updated_at  <  $2
  AND NOT EXISTS (SELECT 1 FROM oss_object_meta m WHERE m.task_id = task.id)
ORDER BY updated_at
LIMIT $3
`

type ScanSettledNeedingStoreParams struct {
	UrlValidAfter sql.NullTime `json:"url_valid_after"`
	StaleBefore   time.Time    `json:"stale_before"`
	BatchSize     int32        `json:"batch_size"`
}

// 转存恢复扫描（6b fetch reconciler 兜底丢失 / 失败的 store job）：
// 扫「COMPLETED 来源已 SETTLED（error_code 为空）、结算超阈值仍无 oss_object_meta、且上游 URL 仍在
// 24h 有效窗口内」的任务 → 调用方幂等重投 store。
//   - status='SETTLED' + error_code IS NULL ⟺ COMPLETED 来源成功结算（失败来源 error_code 非空；
//     缺 usage 者为 SETTLE_FAILED，状态不同，均被排除）。
//   - terminal_at >= @url_valid_after（= now-24h）：上游 video_url 仅 24h 有效，超窗无法转存 → 不再扫
//     （转人工对账，避免无效重投）。
//   - updated_at < @stale_before（= now-阈值）：只扫结算已过阈值仍无 meta 者，避让正常 store job 刚跑的新任务。
func (q *Queries) ScanSettledNeedingStore(ctx context.Context, arg ScanSettledNeedingStoreParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanSettledNeedingStore, arg.UrlValidAfter, arg.StaleBefore, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
