// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertOutboxEvent = `-- name: InsertOutboxEvent :one


INSERT INTO webhook_event_outbox (
    business_account_id, event_type, payload,
    is_financial, retention_until,
    delivery_status, delivery_attempts,
    delivery_idempotency_key
) VALUES (
    $1::text, $2, $3,
    $4, $5,
    'pending', 0,
    $6
)
RETURNING event_id, business_account_id, event_type, payload, is_financial, retention_until,
          delivery_status, delivery_attempts, locked_by, locked_until,
          delivery_idempotency_key, last_pushed_at, created_at
`

type InsertOutboxEventParams struct {
	BusinessAccountID      pgtype.Text `json:"business_account_id"`
	EventType              string      `json:"event_type"`
	Payload                []byte      `json:"payload"`
	IsFinancial            bool        `json:"is_financial"`
	RetentionUntil         time.Time   `json:"retention_until"`
	DeliveryIdempotencyKey string      `json:"delivery_idempotency_key"`
}

// outbox.sql —— webhook_event_outbox 写路径
//
// 本工作流仅实现 INSERT；dispatcher（claim/lease 抢占 + 推送 + DLQ）由 C-min 落地。
// 同事务 INSERT outbox event；retention_until / is_financial / delivery_idempotency_key 由调用方算好。
// delivery_status 默认 'pending'，等待 dispatcher 扫描。
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (WebhookEventOutbox, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.BusinessAccountID,
		arg.EventType,
		arg.Payload,
		arg.IsFinancial,
		arg.RetentionUntil,
		arg.DeliveryIdempotencyKey,
	)
	var i WebhookEventOutbox
	err := row.Scan(
		&i.EventID,
		&i.BusinessAccountID,
		&i.EventType,
		&i.Payload,
		&i.IsFinancial,
		&i.RetentionUntil,
		&i.DeliveryStatus,
		&i.DeliveryAttempts,
		&i.LockedBy,
		&i.LockedUntil,
		&i.DeliveryIdempotencyKey,
		&i.LastPushedAt,
		&i.CreatedAt,
	)
	return i, err
}
