// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// 鉴权热路径：账户是否被授权使用该 model（提交前校验）。
	CheckEntitlement(ctx context.Context, arg CheckEntitlementParams) (bool, error)
	// ============================================================================
	// 4. account_model_concurrency（R15 并发硬上限：原子 claim / release）
	// ============================================================================
	// R15 原子占位（提交前，与 task 落库同事务）：每 (account, model) 计数行 +1，
	// 仅当 inflight < @cap_limit。首次用 ON CONFLICT lazy upsert。
	// 返回新 inflight；**返 0 行（pgx.ErrNoRows）= 占不到 = 调用方返 429**。
	// 用条件 UPSERT（单语句原子，PG 行锁串行化），杜绝 count-then-act 的幻读 TOCTOU。
	// **cap=0 守卫**：INSERT...SELECT 的 `WHERE @cap_limit >= 1` 让首次插入路径也受 cap 约束——
	//   否则「行不存在 + cap=0」会绕过 ON CONFLICT 的 WHERE（仅作用于 DO UPDATE 分支）
	//   直接插入 inflight=1，使「禁用模型(cap=0)」失效（评审 #1）。
	ClaimConcurrencySlot(ctx context.Context, arg ClaimConcurrencySlotParams) (int32, error)
	// 结算（无残余，actualCost == reserveAmount）：只 INSERT commit + UPDATE balance。
	// 与 CommitWithReleaseAtomic 同语义，但少一条 release entry，sqlc 类型推导更干净。
	CommitAtomic(ctx context.Context, arg CommitAtomicParams) (CommitAtomicRow, error)
	// 结算（含部分释放残余）：actualCost < reserveAmount 时用本 query。
	// 一次性 INSERT commit + release 两条 entry + UPDATE balance。
	// CAS：不查 frozen；含 reserved >= @reserve_amount AND version=?
	//
	// 参数：
	//   @reserve_amount, @actual_cost, @release_amount = reserve_amount - actual_cost
	//   @release_correlation_id = correlation_id + ":release"
	//
	// 返回 commit + release 两条 ledger 信息 + 新 balance。
	CommitWithReleaseAtomic(ctx context.Context, arg CommitWithReleaseAtomicParams) (CommitWithReleaseAtomicRow, error)
	// ============================================================================
	// 2. 状态机 CAS（显式 from → to；:execrows 判成败）
	// ============================================================================
	// 通用状态 CAS：仅当当前 status = @from_status 时推进到 @to_status。
	// 用于无附带字段的转移（如 UPSTREAM_SUBMITTED→SETTLING、SETTLING→SETTLED/SETTLE_FAILED）。
	CompareAndSwapTaskStatus(ctx context.Context, arg CompareAndSwapTaskStatusParams) (int64, error)
	// ============================================================================
	// 3. recover / reconciler 扫描 + 在途计数（metrics / 兜底，非 R15 cap）
	// ============================================================================
	// 统计某 (account, model) 当前在途任务数（reconciler 对账 / metrics 用）。
	// **非** R15 cap 计数——cap 由 account_model_concurrency 原子 claim 承载（ADR-0006 决策 2）。
	CountInflightByAccountModel(ctx context.Context, arg CountInflightByAccountModelParams) (int64, error)
	// business_account.sql —— 业务账户 CRUD
	//
	// 适用范围：账户创建（同事务建 balance 行）/ 读取 / 入口 active 校验。
	// 实现层：internal/ledger/postgres.go CreateAccount + 通用查询。
	//
	// 说明：CreateBusinessAccount 仅插入 business_account 主表；
	//       同事务的 business_account_balance(zeros) 由调用方在同一 pgx.Tx 中
	//       另起一条 INSERT（详见 ledger.sql 与 service 实现），便于复用 BalanceRow。
	// 创建业务账户主记录；调用方负责在同一事务内插入 balance(zeros) 与 outbox 事件。
	CreateBusinessAccount(ctx context.Context, arg CreateBusinessAccountParams) (BusinessAccount, error)
	// 创建账户的零值 balance 行（与 CreateBusinessAccount 同事务）。
	CreateBusinessAccountBalanceZero(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error)
	// 硬删除渠道（运营慎用；返回受影响行数判断是否存在）。
	DeleteChannel(ctx context.Context, id int64) (int64, error)
	// 鉴权热路径：根据 token_hash 单 query 查活跃 token（未 revoke + 未过期）。
	// service 层调用前先算 hex = hex.EncodeToString(HMAC-SHA-256(pepper, plaintext))。
	FindActiveAdminTokenByHash(ctx context.Context, tokenHash string) (FindActiveAdminTokenByHashRow, error)
	// 鉴权热路径：根据 key_hash 单 row 查活跃 key（未 revoke）。
	// service 层调用前先算 hex = hex.EncodeToString(HMAC-SHA-256(pepper, plaintext))。
	FindActiveBusinessKeyByHash(ctx context.Context, keyHash string) (BusinessAccountApiKey, error)
	// Commit/Release 前置校验：找同 correlation_id 的 active reserve（未 commit / release）。
	// NOT EXISTS 子查询确认同 correlation_id 没有 commit/release entry。
	FindActiveReserveByCorrelation(ctx context.Context, arg FindActiveReserveByCorrelationParams) (FindActiveReserveByCorrelationRow, error)
	// 按 id 查 token（不限制是否 revoked / expired，运维查询用）。
	FindAdminTokenByID(ctx context.Context, id int64) (FindAdminTokenByIDRow, error)
	// 用于区分「未找到 reserve」与「reserve 已 commit/release」（service 用以返回不同 sentinel）。
	FindAnyReserveByCorrelation(ctx context.Context, arg FindAnyReserveByCorrelationParams) (FindAnyReserveByCorrelationRow, error)
	// 按 id 查 key（不限制是否 revoked，运维 / audit 用）。
	FindBusinessKeyByID(ctx context.Context, id int64) (BusinessAccountApiKey, error)
	// 通用反查：Reserve/Commit/Release/Refund 幂等用此 query 检查同 correlation_id+entry_type 是否已存在。
	FindLedgerEntryByCorrelationAndType(ctx context.Context, arg FindLedgerEntryByCorrelationAndTypeParams) (FindLedgerEntryByCorrelationAndTypeRow, error)
	// ============================================================================
	// 2. 幂等查询
	// ============================================================================
	// 充值幂等命中查询：service 命中后比对 canonical_body_sha256，相同返原 entry，不同 ErrIdempotencyConflict。
	FindLedgerEntryByIdempotencyKey(ctx context.Context, arg FindLedgerEntryByIdempotencyKeyParams) (FindLedgerEntryByIdempotencyKeyRow, error)
	// 冻结账户余额：CAS 含 frozen=false AND version=?
	// 已 frozen 返回 0 行；service 判幂等成功（不视为错误）。
	// 不写 ledger entry（frozen 是 balance 字段，不涉及金额流水）；调用方自行写 outbox。
	FreezeAtomic(ctx context.Context, arg FreezeAtomicParams) (BusinessAccountBalance, error)
	// 按渠道名解析启用渠道的 id（Unit 10 提交流程：catalog 绑定的 channel 名 → channel_id）。
	// name 唯一；不命中 / 已停用返 0 rows → 调用方 ErrChannelNotFound（fail-closed，模型不可用）。
	GetActiveChannelIDByName(ctx context.Context, name string) (int64, error)
	// balance.sql —— 账户余额投影读取
	//
	// 写路径由 ledger.sql 的 CTE 单语句完成（INSERT ledger + UPDATE balance）；
	// 本文件仅承载读路径 + rebuild 专用的 ReplaceBalance（绕过 CAS 的写）。
	// 标准读取：用于 service.GetBalance + admin-cli 反查 + 测试断言。
	GetBalance(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error)
	// 行级 FOR UPDATE 读：rebuild TX3 用，防并发 Commit/Release 写入。
	GetBalanceForUpdate(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error)
	// 事务内读取：与 GetBalance 等价，但显式由 service 在 CAS 失败后的同一 tx 调用。
	// 保留独立 query 命名，便于 grep 出「事务内读」语义。
	GetBalanceInTx(ctx context.Context, businessAccountID string) (BusinessAccountBalance, error)
	// 读取业务账户主记录（用于反查 / 管理后台展示）。
	GetBusinessAccount(ctx context.Context, id string) (BusinessAccount, error)
	// 入口校验：仅返回 status + isolation_required，避免拉全字段；
	// service 层在写操作入口先调用此 query 判 status='active'。
	GetBusinessAccountForActiveCheck(ctx context.Context, id string) (GetBusinessAccountForActiveCheckRow, error)
	// 按 id 查渠道（含密文；service 层即用即解、不回显明文）。
	GetChannelByID(ctx context.Context, id int64) (Channel, error)
	// 查熔断器状态；middleware 在 CheckCircuitBreaker 时调用。
	// 不存在 token_id 时返 0 rows（service 视作未熔断）。
	GetCircuitState(ctx context.Context, tokenID int64) (GetCircuitStateRow, error)
	// 读某 (account, model) 当前 inflight（admin / metrics）。
	GetConcurrency(ctx context.Context, arg GetConcurrencyParams) (AccountModelConcurrency, error)
	// ============================================================================
	// 4. rebuild 全量读
	// ============================================================================
	// rebuild TX2 用：按 id ASC 全量取 ledger，应用层累加得 expected balance。
	// ORDER BY id 保证回放顺序与原写入顺序一致（虽然累加是可交换的，方便审计）。
	GetLedgerEntriesForRebuild(ctx context.Context, businessAccountID string) ([]GetLedgerEntriesForRebuildRow, error)
	// 按 task_id 取产物元数据（store 幂等判存 + Unit 10 GET 现签 URL 用）。不命中返 0 rows。
	GetOSSObjectMetaByTask(ctx context.Context, taskID string) (OssObjectMetum, error)
	// 内部按 id 查任务（worker / reconciler 用，不做归属过滤）。
	GetTaskByID(ctx context.Context, id string) (Task, error)
	// 按上游 task_id 反查本地任务（回调入口 / fetch reconciler 用）。
	GetTaskByUpstreamTaskID(ctx context.Context, upstreamTaskID pgtype.Text) (Task, error)
	// 业务侧只读查询：强制归属校验（id + business_account_id）。
	// 不匹配返 0 rows → handler 返 404（跨租户不可枚举，符合 CLAUDE.md ISP / 失败优先）。
	GetTaskForAccount(ctx context.Context, arg GetTaskForAccountParams) (Task, error)
	// 查指定 token 当日用量；不存在则返 0 rows（service 层视作 0 用量）。
	// day 同样按 UTC（与累加 query 对齐）。
	GetTokenUsage(ctx context.Context, tokenID int64) (GatewayAdminTokenUsage, error)
	// entitlement.sql —— 账户×模型授权 grant / revoke / check
	//
	// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 10/11）
	// 语义：行存在 = 已授权；revoke = 删行；check = 存在性。复合主键 (account, gateway_model)。
	// 授权账户使用某 gateway model；幂等（重复 grant 仅刷新 updated_at，不报错）。
	GrantEntitlement(ctx context.Context, arg GrantEntitlementParams) (BusinessAccountModelEntitlement, error)
	// ============================================================================
	// 2. Token 每日用量累计
	// ============================================================================
	// 单语句原子累加当日用量；不存在则 INSERT，存在则 UPDATE 累加。
	// 三列分别累加（recharge / refund / create）；调用方按场景传非零的那一列，其他传 0。
	// day 用 UTC 当日（决策 D9）。
	IncrementTokenUsage(ctx context.Context, arg IncrementTokenUsageParams) (GatewayAdminTokenUsage, error)
	// admin_token.sql —— Admin Token CRUD + 阀门用量累计 + 熔断器状态机
	//
	// 设计文档：docs/multimedia-gateway-design.md §9bis.6（Admin Token 安全 5 件套）
	// 实施计划：docs/plans/2026-05-27-003-feat-workflow-d-min-admin-api-plan.md Unit 1
	//
	// 命名约定：
	//   - InsertAdminToken / FindActiveAdminTokenByHash / RevokeAdminToken / ListActiveAdminTokens：token CRUD
	//   - IncrementTokenUsage / GetTokenUsage：每日用量累计 + 查询
	//   - RecordCircuitError / TripCircuitBreaker / GetCircuitState / ResetCircuitBreaker：熔断器状态机
	//
	// 关键 PG 语义：
	//   - ON CONFLICT DO UPDATE：用于 UPSERT 同行原子累加，行锁串行化保证 100+ 并发同行无丢失
	//   - COALESCE(revoked_at, NOW())：Revoke 同 token 多次时保留首次 revoke 时间戳，幂等成功
	//   - CASE WHEN 在 DO UPDATE SET 子句中：实现 circuit 1h 滚动窗口的"超时即重置"
	// ============================================================================
	// 1. Admin Token CRUD
	// ============================================================================
	// 插入新 Admin Token；调用方负责生成 plaintext + HMAC-SHA-256(pepper, plaintext) → token_hash hex。
	// 7 个阀门字段 NULL = 无限制；ip_allowlist 至少 1 个 CIDR（service 层校验，schema 不强制）。
	InsertAdminToken(ctx context.Context, arg InsertAdminTokenParams) (InsertAdminTokenRow, error)
	// business_account_api_key.sql —— 业务侧 API Key CRUD + 鉴权热路径
	//
	// 设计文档：docs/multimedia-gateway-design.md §9
	// 实施计划：docs/plans/2026-05-27-004-feat-workflow-f-min-openai-compat-relay-plan.md Unit 1
	//
	// 命名约定：
	//   - InsertBusinessKey / FindActiveBusinessKeyByHash / FindBusinessKeyByID / RevokeBusinessKey：CRUD
	//   - ListActiveBusinessKeysByAccount / ListAllActiveBusinessKeys：admin-cli 与运维查询
	//   - TouchBusinessKeyLastUsed：异步 best-effort 鉴权命中时间戳
	//
	// 关键 PG 语义：
	//   - UNIQUE on key_hash：鉴权热路径单 row 查询（O(log n) btree）
	//   - COALESCE(revoked_at, NOW())：Revoke 多次同 id 保留首次 timestamp（与 admin token 一致）
	//   - WHERE revoked_at IS NULL：所有"active key"查询都过滤已吊销，零额外索引开销
	// ============================================================================
	// 1. CRUD
	// ============================================================================
	// 插入新业务 key；调用方负责生成 plaintext + HMAC-SHA-256(pepper, plaintext) → key_hash hex。
	// requests_per_minute NULL = 不限速；service 层校验 > 0（DB CHECK 也兜底）。
	InsertBusinessKey(ctx context.Context, arg InsertBusinessKeyParams) (BusinessAccountApiKey, error)
	// channel.sql —— 渠道（上游 provider 凭据抽象）CRUD + 路由热路径查询
	//
	// 设计文档：docs/multimedia-gateway-design.md §8.2
	// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 3 channel service）
	//
	// 安全约定：credentials_encrypted 是 envelope 密文（AES-GCM，KEK），明文绝不入库；
	//   key_version 标记加密用的 KEK 版本，支持轮换（ADR-0006 决策 4）。
	// 创建渠道；credentials_encrypted 由 service 层（Unit 3）用 KEK 加密后传入。
	InsertChannel(ctx context.Context, arg InsertChannelParams) (Channel, error)
	// oss_object_meta.sql —— TOS 结果对象元数据 CRUD + 转存恢复扫描（Phase 2 Unit 9）
	//
	// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 9
	// 决策：ADR-0006 决策 3（官方 TOS SDK；结果对象 + 受限签名 URL）
	//
	// 不存签名 URL / 上游源 URL（见 migration 0010 说明）；PK=task_id 天然幂等。
	// 记录转存产物元数据；ON CONFLICT DO NOTHING 实现幂等（重复 store / 并发重投命中 PK 冲突 → 0 行）。
	// 返回受影响行数：1 = 本次插入，0 = 已存在（幂等跳过）。
	InsertOSSObjectMeta(ctx context.Context, arg InsertOSSObjectMetaParams) (int64, error)
	// outbox.sql —— webhook_event_outbox 写路径
	//
	// 本工作流仅实现 INSERT；dispatcher（claim/lease 抢占 + 推送 + DLQ）由 C-min 落地。
	// 同事务 INSERT outbox event；retention_until / is_financial / delivery_idempotency_key 由调用方算好。
	// delivery_status 默认 'pending'，等待 dispatcher 扫描。
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (WebhookEventOutbox, error)
	// task.sql —— 异步任务 CRUD + 状态机 CAS + recover/reconciler 扫描 + R15 并发计数行
	//
	// 设计文档：docs/multimedia-gateway-design.md §9 / §9ter / §9.5
	// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 6/8）
	// 决策：ADR-0006（状态机 CAS 必带 from 条件；R15 走 account_model_concurrency 原子 claim）
	//
	// 硬约束（CLAUDE.md 状态机模式）：所有状态变更**只**走带 from 条件的 CAS（:execrows，
	//   受影响 0 行 = CAS 失败 = 状态已被他人推进）；**禁止**裸 UPDATE ... WHERE id 不带 status。
	// ============================================================================
	// 1. CRUD
	// ============================================================================
	// 提交流程落库（status 默认 SUBMITTED）；token_id / channel_id / callback_token 可空。
	InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error)
	// 列出所有活跃 token（未 revoke）；按 created_at DESC 排序便于运维查最新发放。
	// 返回**不含** token_hash（避免泄漏；明文已无法获取，hash 也只入审计 / 排查路径）。
	ListActiveAdminTokens(ctx context.Context) ([]ListActiveAdminTokensRow, error)
	// ============================================================================
	// 2. 列表查询（admin-cli list / 运维）
	// ============================================================================
	// 列出指定账户的所有活跃 key（未 revoke）；按 created_at DESC 排序便于运维查最新发放。
	// **不**返 key_hash（避免泄漏；明文已无法获取，hash 也只入鉴权 / 排查路径）。
	ListActiveBusinessKeysByAccount(ctx context.Context, businessAccountID string) ([]ListActiveBusinessKeysByAccountRow, error)
	// 列出所有启用的渠道（路由候选 / 运营列表）。
	ListActiveChannels(ctx context.Context) ([]Channel, error)
	// 按 provider_type 列出启用的渠道（工厂按 provider 选 adapter 时用）。
	ListActiveChannelsByProvider(ctx context.Context, providerType string) ([]Channel, error)
	// 列出所有账户的活跃 key；admin-cli `business-key list`（不带 --business-account-id）用。
	// **不**返 key_hash。按 created_at DESC 排序。
	ListAllActiveBusinessKeys(ctx context.Context) ([]ListAllActiveBusinessKeysRow, error)
	// reconciler 全表扫起点：仅取 ID + 当前 version；后续读 SUM 时再单只读 tx 中拉一致快照。
	ListAllUnfrozenAccountsForReconciler(ctx context.Context) ([]ListAllUnfrozenAccountsForReconcilerRow, error)
	// 列出账户的全部授权 model（admin / 运维）。
	ListEntitlementsByAccount(ctx context.Context, businessAccountID string) ([]BusinessAccountModelEntitlement, error)
	// reconciler 收尾 watchdog：扫出处于 rebuild_in_progress 状态且 frozen 时间过长的账户。
	//
	// 用途：U8 RebuildBalance 三事务流程中第二阶段崩溃 / 进程被 kill 时，账户会停留在
	// frozen=true + reason 含 'rebuild_in_progress' 状态；本查询给 reconciler 暴露 metric
	// 让运维及时发现并人工恢复（pass-2 sec sec-pass2-008）。
	//
	// @threshold 参数取自 reconciler.rebuildStuckThreshold（默认 10 分钟）。
	ListStuckRebuildAccounts(ctx context.Context, threshold pgtype.Interval) ([]ListStuckRebuildAccountsRow, error)
	// CAS SUBMITTED → UPSTREAM_SUBMITTING，并写入 worker 抢占 lease（submit_locked_*）。
	// 仅一个 worker 能 CAS 成功；其余受影响 0 行放弃。
	MarkTaskSubmitting(ctx context.Context, arg MarkTaskSubmittingParams) (int64, error)
	// CAS UPSTREAM_SUBMITTING → UPSTREAM_SUBMITTED，同步持久化 upstream_task_id + 提交时刻。
	// 这是「上游 Submit 成功 → 存 upstream_task_id」的原子落点（ADR-0006 决策 5 双提交防护核心）。
	MarkTaskUpstreamSubmitted(ctx context.Context, arg MarkTaskUpstreamSubmittedParams) (int64, error)
	// CAS 进入上游终态（COMPLETED/FAILED/CANCELLED/EXPIRED），写 terminal_at + 错误信息，
	// 并**置空 callback_token**（终态后不再接受回调，防 token 泄露后被滥用，ADR-0006 决策 5）。
	// 调用方负责在同事务内释放并发 claim（ReleaseConcurrencySlot）。
	MarkTaskUpstreamTerminal(ctx context.Context, arg MarkTaskUpstreamTerminalParams) (int64, error)
	// ledger.sql —— 账本流水写入 + 幂等查询 + drift 聚合 + rebuild 全量读
	//
	// 设计文档：docs/multimedia-gateway-design.md §3ter
	// 实施计划：docs/plans/2026-05-26-002-...-plan.md Unit 2
	//
	// 写操作统一走 PG CTE 单语句模式：
	//   WITH new_entry AS (INSERT INTO business_account_ledger ... RETURNING ...)
	//   UPDATE business_account_balance SET ... WHERE CAS 条件 RETURNING ...
	//
	// 关键 PG 语义（务必牢记）：
	//   data-modifying CTE 即使最终 SELECT 0 行，sibling INSERT 仍**执行到完成**。
	//   原子性靠 tx 级 ROLLBACK 保证 —— service 在 pgx.ErrNoRows 时**必须**显式 tx.Rollback。
	//
	// sqlc 命名参数注意：
	//   sqlc v1.30.0 对 `-@param`（紧贴一元负号）解析有 bug，会把 `@param` 留在生成 SQL 中。
	//   解决：所有负值表达式写成 `(0 - @param)::bigint`，sqlc 能正确替换为 `(0 - $N)::bigint`。
	//
	// CAS 字段策略：
	//   - Recharge / Reserve   含 frozen = false（拒绝冻结账户的新入金 / 预占）
	//   - Commit / Release / Refund / Freeze / Unfreeze   不查 frozen（允许 inflight 完成 + 管理动作）
	//   - 所有写都含 version = @expected_version 防丢失更新
	// ============================================================================
	// 1. 写操作：CTE 单语句（INSERT ledger + UPDATE balance）
	// ============================================================================
	// 充值：available 增 + recharge_total 增；CAS WHERE frozen=false AND version=?
	// 0 行 = CAS 失败（frozen / version 冲突）；service 同 tx 内 fresh-read 判错。
	RechargeAtomic(ctx context.Context, arg RechargeAtomicParams) (RechargeAtomicRow, error)
	// ============================================================================
	// 3. 熔断器状态机
	// ============================================================================
	// 错误计数 + 1h 滚动窗口自动重置（document-review feasibility #8 完整 SQL）。
	// 行为：
	//   - 不存在 token_id → INSERT (window_started_at=NOW(), error_count=1)
	//   - 存在但 window_started_at < NOW() - 1h → 重置窗口（error_count=1, window_started_at=NOW()）
	//   - 存在且窗口内 → error_count + 1
	// 单语句完成所有路径，行锁串行化保证 50+ 并发同 token error_count 最终 = 实际错误数。
	RecordCircuitError(ctx context.Context, tokenID int64) (RecordCircuitErrorRow, error)
	// 退款：used_total 减 + available 增 + refund_total 增；CAS 含 used_total >= @amount AND version=?
	// 不查 frozen（管理动作允许）。refund_total 不进不变量等式，单独自增。
	RefundAtomic(ctx context.Context, arg RefundAtomicParams) (RefundAtomicRow, error)
	// 释放预占：reserved 减 + available 增；CAS 含 reserved >= @amount AND version=?
	// 不查 frozen（允许 inflight 完成）。
	ReleaseAtomic(ctx context.Context, arg ReleaseAtomicParams) (ReleaseAtomicRow, error)
	// 释放并发槽（进上游终态 CAS 赢家同事务内调用）：inflight -1，永不为负（防 double-release）。
	ReleaseConcurrencySlot(ctx context.Context, arg ReleaseConcurrencySlotParams) (int64, error)
	// rebuild TX3 专用：用 last_ledger_id CAS 校验「TX2 读快照后没有新 entry 写入」；
	// 命中行数 = 0 表示并发漂移，调用方应回到 TX2 重读快照。
	// 不参与日常写路径，绕开 version CAS（rebuild 期间 frozen=true 已阻新业务写）。
	ReplaceBalance(ctx context.Context, arg ReplaceBalanceParams) (int64, error)
	// 预占：available 减 + reserved 增；CAS 含 available >= @amount AND frozen=false AND version=?
	// available_delta 用 (0::bigint - @amount)::bigint 表达负值（sqlc 解析必须）。
	ReserveAtomic(ctx context.Context, arg ReserveAtomicParams) (ReserveAtomicRow, error)
	// 运维手工解锁熔断器（admin-cli circuit-reset 推 P1）。
	// 重置 error_count 与 window，清 breaker_tripped_until。
	ResetCircuitBreaker(ctx context.Context, tokenID int64) (ResetCircuitBreakerRow, error)
	// Revoke 给定 id 的 token。
	// 用 COALESCE(revoked_at, NOW()) 保留首次 revoke 时间戳，多次 Revoke 同 id 不覆盖原 timestamp。
	// 返回值（id + 新 revoked_at + 原 revoked_at）让 service 区分"首次 revoke" vs "已 revoked 幂等"。
	// 不存在 id 时返 0 rows（service 层判 ErrTokenNotFound）。
	RevokeAdminToken(ctx context.Context, id int64) (RevokeAdminTokenRow, error)
	// Revoke 给定 id 的 key。
	// COALESCE 保留首次 revoke 时间戳（与 admin token 一致）；多次 Revoke 同 id 不覆盖。
	// 不存在 id 时返 0 rows（service 层判 ErrKeyNotFound）。
	RevokeBusinessKey(ctx context.Context, id int64) (RevokeBusinessKeyRow, error)
	// 撤销授权（删行）；返回受影响行数判断是否原本存在。
	RevokeEntitlement(ctx context.Context, arg RevokeEntitlementParams) (int64, error)
	// expire worker：扫上游侧仍在途但已超最长执行期的任务 → CAS→EXPIRED + release 兜底。
	ScanExpirableTasks(ctx context.Context, arg ScanExpirableTasksParams) ([]Task, error)
	// ============================================================================
	// 5. orphan reserve sweep（跨表：ledger active reserve 反查无对应 task 行）
	// ============================================================================
	// orphan reserve sweep（6b / 计划 Unit 6 Approach）：扫 ledger 中尚未结算的视频任务 reserve
	// （reference_type='video_task'）反查在 task 表无对应行者 → 调用方 Release 回退（无 orphan 占资金）。
	//   - 未结算：同 reserve 既无 commit、也无 release（注意账本写入约定：commit entry 记在 base
	//     correlation 下，**全额/残余 release entry 记在 correlation||':release' 下**——见 ledger
	//     postgres.go Release/CommitWithReleaseAtomic）。故须同时排除两者，否则已被本 sweep（或正常
	//     settleReleased）回退过的 reserve 因其 release 记在 ':release' 下而被反复误判为孤儿、每轮重扫。
	//   - 无 task 行：reference_id（= 提交时的 task_id）在 task 表不存在 = reserve 落了但 task tx 没成。
	//     reference_id IS NOT NULL 守卫：NULL 时 t.id = NULL 恒 false 会把 NULL-ref reserve 误判为孤儿。
	//   - @max_created_at = now - 最小年龄阈值：**只回收确陈旧者**，避免误回收 in-flight 窗口内
	//     「reserve 已落、claim+task tx 即将提交」的 reserve（否则该 task settle 反查不到 reserve →
	//     ErrReserveNotFound → 资金锁死）。阈值须 ≫ reserve→task tx 正常间隔（计划 Risks）。
	// 复用 idx_ledger_reference (reference_type, reference_id) 过滤 video_task（MVP 视频 ledger 行少）。
	ScanOrphanVideoReserves(ctx context.Context, arg ScanOrphanVideoReservesParams) ([]ScanOrphanVideoReservesRow, error)
	// recover worker：扫 UPSTREAM_SUBMITTING 且 lease 过期的任务（崩溃在提交窗口）。
	// ADR-0006 决策 5：上游无幂等键/不可反查 → 这些任务 fail-closed（不自动重投），
	// 调用方据此 CAS→FAILED + release + 告警。用 idx_task_submit_recover。
	ScanRecoverableTasks(ctx context.Context, arg ScanRecoverableTasksParams) ([]Task, error)
	// 转存恢复扫描（6b fetch reconciler 兜底丢失 / 失败的 store job）：
	// 扫「COMPLETED 来源已 SETTLED（error_code 为空）、结算超阈值仍无 oss_object_meta、且上游 URL 仍在
	// 24h 有效窗口内」的任务 → 调用方幂等重投 store。
	//   - status='SETTLED' + error_code IS NULL ⟺ COMPLETED 来源成功结算（失败来源 error_code 非空；
	//     缺 usage 者为 SETTLE_FAILED，状态不同，均被排除）。
	//   - terminal_at >= @url_valid_after（= now-24h）：上游 video_url 仅 24h 有效，超窗无法转存 → 不再扫
	//     （转人工对账，避免无效重投）。
	//   - updated_at < @stale_before（= now-阈值）：只扫结算已过阈值仍无 meta 者，避让正常 store job 刚跑的新任务。
	ScanSettledNeedingStore(ctx context.Context, arg ScanSettledNeedingStoreParams) ([]Task, error)
	// fetch reconciler（6b）：扫 SETTLING 滞留超阈值的任务——硬崩溃于 commit/release 落账后、
	// 终态 CAS（SETTLING→SETTLED/SETTLE_FAILED）前，task 卡 SETTLING（钱可能已落账、态未终）。
	// 调用方幂等重投 settle 恢复：先反查 active reserve 判钱是否已落账，已落账→直接 finalize SETTLED，
	// 未落账→按 error_code 判 COMPLETED/失败重走结算（靠账本 ErrAlreadySettled / 反查收敛）。
	// 用 idx_task_stuck_settling（0009）。阈值须 ≫ 正常 settle 端到端耗时，避免抢正在结算中的任务。
	ScanStuckSettling(ctx context.Context, arg ScanStuckSettlingParams) ([]Task, error)
	// fetch reconciler：扫 UPSTREAM_SUBMITTED 超时未终态的任务 → 主动 Poll 上游兜底。
	ScanStuckUpstreamSubmitted(ctx context.Context, arg ScanStuckUpstreamSubmittedParams) ([]Task, error)
	// reconciler：扫 SUBMITTED 滞留超阈值（入队丢失 / Redis 抖动导致无 Asynq job）→ 幂等重投。
	ScanSubmittedNoJob(ctx context.Context, arg ScanSubmittedNoJobParams) ([]Task, error)
	// 启用 / 停用渠道（软下线优先于硬删除）。
	SetChannelEnabled(ctx context.Context, arg SetChannelEnabledParams) (SetChannelEnabledRow, error)
	// ============================================================================
	// 3. drift reconciler 聚合
	// ============================================================================
	// reconciler 用：对单个账户的全部 ledger entry SUM 各 delta，
	// 与 balance 表比对得 drift。recharge_sum / refund_sum 用 FILTER 仅累加对应 entry_type。
	// COALESCE 兜底 NULL（账户 0 条 ledger 时 SUM 返回 NULL）。
	SumLedgerDeltasByAccount(ctx context.Context, businessAccountID string) (SumLedgerDeltasByAccountRow, error)
	// ============================================================================
	// 3. 鉴权命中异步更新（best-effort）
	// ============================================================================
	// 异步批量更新 last_used_at（service 层 5min 批量 flush）；single id 更新。
	// 运维用途：清理长期未用 key（如 WHERE last_used_at < NOW() - INTERVAL '90 days'）。
	// best-effort：失败不影响鉴权主路径；service 层会捕获并 log 但不返业务错。
	TouchBusinessKeyLastUsed(ctx context.Context, id int64) error
	// 跳闸：把 breaker_tripped_until 写为 NOW() + 1h；service 在 RecordCircuitError 返 error_count ≥ 100 时调。
	// 已跳闸 token 重复调用：tripped_until 取较大值（不会缩短跳闸期）。
	TripCircuitBreaker(ctx context.Context, tokenID int64) (TripCircuitBreakerRow, error)
	// 解冻：CAS 含 frozen=true AND version=?；frozen_reason 重写为新值（rebuild_completed / manual_unfreeze）。
	// 0 行 = 已 unfrozen（幂等成功）或 version 冲突。
	UnfreezeAtomic(ctx context.Context, arg UnfreezeAtomicParams) (BusinessAccountBalance, error)
	// 更新渠道凭据密文 + KEK 版本（凭据轮换 / KEK 重加密命令用，ADR-0006 决策 4）。
	// 仅动密文与版本，不碰其他配置；明文绝不入库。
	UpdateChannelCredentials(ctx context.Context, arg UpdateChannelCredentialsParams) (Channel, error)
}

var _ Querier = (*Queries)(nil)
