// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimConcurrencySlot = `-- name: ClaimConcurrencySlot :one


INSERT INTO account_model_concurrency AS amc (business_account_id, model, inflight, updated_at)
SELECT $1, $2, 1, NOW()
WHERE $3::int >= 1
ON CONFLICT (business_account_id, model) DO UPDATE
    SET inflight   = amc.inflight + 1,
        updated_at = NOW()
    WHERE amc.inflight < $3
RETURNING inflight
`

type ClaimConcurrencySlotParams struct {
	BusinessAccountID string `json:"business_account_id"`
	Model             string `json:"model"`
	CapLimit          int32  `json:"cap_limit"`
}

// ============================================================================
// 4. account_model_concurrency（R15 并发硬上限：原子 claim / release）
// ============================================================================
// R15 原子占位（提交前，与 task 落库同事务）：每 (account, model) 计数行 +1，
// 仅当 inflight < @cap_limit。首次用 ON CONFLICT lazy upsert。
// 返回新 inflight；**返 0 行（pgx.ErrNoRows）= 占不到 = 调用方返 429**。
// 用条件 UPSERT（单语句原子，PG 行锁串行化），杜绝 count-then-act 的幻读 TOCTOU。
// **cap=0 守卫**：INSERT...SELECT 的 `WHERE @cap_limit >= 1` 让首次插入路径也受 cap 约束——
//
//	否则「行不存在 + cap=0」会绕过 ON CONFLICT 的 WHERE（仅作用于 DO UPDATE 分支）
//	直接插入 inflight=1，使「禁用模型(cap=0)」失效（评审 #1）。
func (q *Queries) ClaimConcurrencySlot(ctx context.Context, arg ClaimConcurrencySlotParams) (int32, error) {
	row := q.db.QueryRow(ctx, claimConcurrencySlot, arg.BusinessAccountID, arg.Model, arg.CapLimit)
	var inflight int32
	err := row.Scan(&inflight)
	return inflight, err
}

const compareAndSwapTaskStatus = `-- name: CompareAndSwapTaskStatus :execrows


UPDATE task
SET status     = $1,
    updated_at = NOW()
WHERE id = $2
  AND status = $3
`

type CompareAndSwapTaskStatusParams struct {
	ToStatus   TaskStatus `json:"to_status"`
	ID         string     `json:"id"`
	FromStatus TaskStatus `json:"from_status"`
}

// ============================================================================
// 2. 状态机 CAS（显式 from → to；:execrows 判成败）
// ============================================================================
// 通用状态 CAS：仅当当前 status = @from_status 时推进到 @to_status。
// 用于无附带字段的转移（如 UPSTREAM_SUBMITTED→SETTLING、SETTLING→SETTLED/SETTLE_FAILED）。
func (q *Queries) CompareAndSwapTaskStatus(ctx context.Context, arg CompareAndSwapTaskStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, compareAndSwapTaskStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countInflightByAccountModel = `-- name: CountInflightByAccountModel :one


SELECT count(*) FROM task
WHERE business_account_id = $1
  AND model = $2
  AND status IN ('SUBMITTED', 'UPSTREAM_SUBMITTING', 'UPSTREAM_SUBMITTED')
`

type CountInflightByAccountModelParams struct {
	BusinessAccountID string `json:"business_account_id"`
	Model             string `json:"model"`
}

// ============================================================================
// 3. recover / reconciler 扫描 + 在途计数（metrics / 兜底，非 R15 cap）
// ============================================================================
// 统计某 (account, model) 当前在途任务数（reconciler 对账 / metrics 用）。
// **非** R15 cap 计数——cap 由 account_model_concurrency 原子 claim 承载（ADR-0006 决策 2）。
func (q *Queries) CountInflightByAccountModel(ctx context.Context, arg CountInflightByAccountModelParams) (int64, error) {
	row := q.db.QueryRow(ctx, countInflightByAccountModel, arg.BusinessAccountID, arg.Model)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getConcurrency = `-- name: GetConcurrency :one
SELECT business_account_id, model, inflight, updated_at FROM account_model_concurrency
WHERE business_account_id = $1
  AND model = $2
`

type GetConcurrencyParams struct {
	BusinessAccountID string `json:"business_account_id"`
	Model             string `json:"model"`
}

// 读某 (account, model) 当前 inflight（admin / metrics）。
func (q *Queries) GetConcurrency(ctx context.Context, arg GetConcurrencyParams) (AccountModelConcurrency, error) {
	row := q.db.QueryRow(ctx, getConcurrency, arg.BusinessAccountID, arg.Model)
	var i AccountModelConcurrency
	err := row.Scan(
		&i.BusinessAccountID,
		&i.Model,
		&i.Inflight,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task WHERE id = $1
`

// 内部按 id 查任务（worker / reconciler 用，不做归属过滤）。
func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.TokenID,
		&i.ChannelID,
		&i.ProviderType,
		&i.Model,
		&i.Status,
		&i.UpstreamTaskID,
		&i.SubmitLockedUntil,
		&i.SubmitLockedBy,
		&i.SubmitRecoverCount,
		&i.FinancialSnapshot,
		&i.AccountingMonth,
		&i.SubmittedAt,
		&i.TerminalAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.UpdatedAt,
		&i.CallbackToken,
		&i.UpstreamSubmittedAt,
	)
	return i, err
}

const getTaskByUpstreamTaskID = `-- name: GetTaskByUpstreamTaskID :one
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task WHERE upstream_task_id = $1
`

// 按上游 task_id 反查本地任务（回调入口 / fetch reconciler 用）。
func (q *Queries) GetTaskByUpstreamTaskID(ctx context.Context, upstreamTaskID pgtype.Text) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByUpstreamTaskID, upstreamTaskID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.TokenID,
		&i.ChannelID,
		&i.ProviderType,
		&i.Model,
		&i.Status,
		&i.UpstreamTaskID,
		&i.SubmitLockedUntil,
		&i.SubmitLockedBy,
		&i.SubmitRecoverCount,
		&i.FinancialSnapshot,
		&i.AccountingMonth,
		&i.SubmittedAt,
		&i.TerminalAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.UpdatedAt,
		&i.CallbackToken,
		&i.UpstreamSubmittedAt,
	)
	return i, err
}

const getTaskForAccount = `-- name: GetTaskForAccount :one
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE id = $1
  AND business_account_id = $2
`

type GetTaskForAccountParams struct {
	ID                string `json:"id"`
	BusinessAccountID string `json:"business_account_id"`
}

// 业务侧只读查询：强制归属校验（id + business_account_id）。
// 不匹配返 0 rows → handler 返 404（跨租户不可枚举，符合 CLAUDE.md ISP / 失败优先）。
func (q *Queries) GetTaskForAccount(ctx context.Context, arg GetTaskForAccountParams) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskForAccount, arg.ID, arg.BusinessAccountID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.TokenID,
		&i.ChannelID,
		&i.ProviderType,
		&i.Model,
		&i.Status,
		&i.UpstreamTaskID,
		&i.SubmitLockedUntil,
		&i.SubmitLockedBy,
		&i.SubmitRecoverCount,
		&i.FinancialSnapshot,
		&i.AccountingMonth,
		&i.SubmittedAt,
		&i.TerminalAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.UpdatedAt,
		&i.CallbackToken,
		&i.UpstreamSubmittedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one




INSERT INTO task (
    id, business_account_id, token_id, channel_id,
    provider_type, model, financial_snapshot, accounting_month,
    callback_token
)
VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9
)
RETURNING id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at
`

type InsertTaskParams struct {
	ID                string      `json:"id"`
	BusinessAccountID string      `json:"business_account_id"`
	TokenID           pgtype.Int8 `json:"token_id"`
	ChannelID         pgtype.Int8 `json:"channel_id"`
	ProviderType      string      `json:"provider_type"`
	Model             string      `json:"model"`
	FinancialSnapshot []byte      `json:"financial_snapshot"`
	AccountingMonth   string      `json:"accounting_month"`
	CallbackToken     pgtype.Text `json:"callback_token"`
}

// task.sql —— 异步任务 CRUD + 状态机 CAS + recover/reconciler 扫描 + R15 并发计数行
//
// 设计文档：docs/multimedia-gateway-design.md §9 / §9ter / §9.5
// 实施计划：docs/plans/2026-05-28-001-feat-async-video-relay-mvp-plan.md Unit 2（供 Unit 6/8）
// 决策：ADR-0006（状态机 CAS 必带 from 条件；R15 走 account_model_concurrency 原子 claim）
//
// 硬约束（CLAUDE.md 状态机模式）：所有状态变更**只**走带 from 条件的 CAS（:execrows，
//
//	受影响 0 行 = CAS 失败 = 状态已被他人推进）；**禁止**裸 UPDATE ... WHERE id 不带 status。
//
// ============================================================================
// 1. CRUD
// ============================================================================
// 提交流程落库（status 默认 SUBMITTED）；token_id / channel_id / callback_token 可空。
func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.ID,
		arg.BusinessAccountID,
		arg.TokenID,
		arg.ChannelID,
		arg.ProviderType,
		arg.Model,
		arg.FinancialSnapshot,
		arg.AccountingMonth,
		arg.CallbackToken,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.BusinessAccountID,
		&i.TokenID,
		&i.ChannelID,
		&i.ProviderType,
		&i.Model,
		&i.Status,
		&i.UpstreamTaskID,
		&i.SubmitLockedUntil,
		&i.SubmitLockedBy,
		&i.SubmitRecoverCount,
		&i.FinancialSnapshot,
		&i.AccountingMonth,
		&i.SubmittedAt,
		&i.TerminalAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.UpdatedAt,
		&i.CallbackToken,
		&i.UpstreamSubmittedAt,
	)
	return i, err
}

const markTaskSubmitting = `-- name: MarkTaskSubmitting :execrows
UPDATE task
SET status              = 'UPSTREAM_SUBMITTING',
    submit_locked_until = $1,
    submit_locked_by    = $2,
    updated_at          = NOW()
WHERE id = $3
  AND status = 'SUBMITTED'
`

type MarkTaskSubmittingParams struct {
	SubmitLockedUntil sql.NullTime `json:"submit_locked_until"`
	SubmitLockedBy    pgtype.Text  `json:"submit_locked_by"`
	ID                string       `json:"id"`
}

// CAS SUBMITTED → UPSTREAM_SUBMITTING，并写入 worker 抢占 lease（submit_locked_*）。
// 仅一个 worker 能 CAS 成功；其余受影响 0 行放弃。
func (q *Queries) MarkTaskSubmitting(ctx context.Context, arg MarkTaskSubmittingParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskSubmitting, arg.SubmitLockedUntil, arg.SubmitLockedBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTaskUpstreamSubmitted = `-- name: MarkTaskUpstreamSubmitted :execrows
UPDATE task
SET status                = 'UPSTREAM_SUBMITTED',
    upstream_task_id      = $1,
    upstream_submitted_at = NOW(),
    updated_at            = NOW()
WHERE id = $2
  AND status = 'UPSTREAM_SUBMITTING'
`

type MarkTaskUpstreamSubmittedParams struct {
	UpstreamTaskID pgtype.Text `json:"upstream_task_id"`
	ID             string      `json:"id"`
}

// CAS UPSTREAM_SUBMITTING → UPSTREAM_SUBMITTED，同步持久化 upstream_task_id + 提交时刻。
// 这是「上游 Submit 成功 → 存 upstream_task_id」的原子落点（ADR-0006 决策 5 双提交防护核心）。
func (q *Queries) MarkTaskUpstreamSubmitted(ctx context.Context, arg MarkTaskUpstreamSubmittedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskUpstreamSubmitted, arg.UpstreamTaskID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markTaskUpstreamTerminal = `-- name: MarkTaskUpstreamTerminal :execrows
UPDATE task
SET status        = $1,
    terminal_at   = NOW(),
    error_code    = $2,
    error_message = $3,
    callback_token = NULL,
    updated_at    = NOW()
WHERE id = $4
  AND status = $5
`

type MarkTaskUpstreamTerminalParams struct {
	ToStatus     TaskStatus  `json:"to_status"`
	ErrorCode    pgtype.Text `json:"error_code"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           string      `json:"id"`
	FromStatus   TaskStatus  `json:"from_status"`
}

// CAS 进入上游终态（COMPLETED/FAILED/CANCELLED/EXPIRED），写 terminal_at + 错误信息，
// 并**置空 callback_token**（终态后不再接受回调，防 token 泄露后被滥用，ADR-0006 决策 5）。
// 调用方负责在同事务内释放并发 claim（ReleaseConcurrencySlot）。
func (q *Queries) MarkTaskUpstreamTerminal(ctx context.Context, arg MarkTaskUpstreamTerminalParams) (int64, error) {
	result, err := q.db.Exec(ctx, markTaskUpstreamTerminal,
		arg.ToStatus,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.ID,
		arg.FromStatus,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const releaseConcurrencySlot = `-- name: ReleaseConcurrencySlot :execrows
UPDATE account_model_concurrency
SET inflight   = inflight - 1,
    updated_at = NOW()
WHERE business_account_id = $1
  AND model = $2
  AND inflight > 0
`

type ReleaseConcurrencySlotParams struct {
	BusinessAccountID string `json:"business_account_id"`
	Model             string `json:"model"`
}

// 释放并发槽（进上游终态 CAS 赢家同事务内调用）：inflight -1，永不为负（防 double-release）。
func (q *Queries) ReleaseConcurrencySlot(ctx context.Context, arg ReleaseConcurrencySlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseConcurrencySlot, arg.BusinessAccountID, arg.Model)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scanExpirableTasks = `-- name: ScanExpirableTasks :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status IN ('SUBMITTED', 'UPSTREAM_SUBMITTING', 'UPSTREAM_SUBMITTED')
  AND submitted_at < $1
ORDER BY submitted_at
LIMIT $2
`

type ScanExpirableTasksParams struct {
	Threshold time.Time `json:"threshold"`
	BatchSize int32     `json:"batch_size"`
}

// expire worker：扫上游侧仍在途但已超最长执行期的任务 → CAS→EXPIRED + release 兜底。
func (q *Queries) ScanExpirableTasks(ctx context.Context, arg ScanExpirableTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanExpirableTasks, arg.Threshold, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanOrphanVideoReserves = `-- name: ScanOrphanVideoReserves :many


SELECT
    l.business_account_id,
    l.correlation_id,
    l.amount,
    l.reference_id,
    l.created_at
FROM business_account_ledger l
WHERE l.entry_type     = 'reserve'
  AND l.reference_type = 'video_task'
  AND l.reference_id IS NOT NULL
  AND l.created_at     < $1
  AND NOT EXISTS (
      SELECT 1 FROM business_account_ledger s
      WHERE s.business_account_id = l.business_account_id
        AND (
              (s.correlation_id = l.correlation_id            AND s.entry_type = 'commit')
           OR (s.correlation_id = l.correlation_id || ':release' AND s.entry_type = 'release')
        )
  )
  AND NOT EXISTS (
      SELECT 1 FROM task t WHERE t.id = l.reference_id
  )
ORDER BY l.created_at
LIMIT $2
`

type ScanOrphanVideoReservesParams struct {
	MaxCreatedAt time.Time `json:"max_created_at"`
	BatchSize    int32     `json:"batch_size"`
}

type ScanOrphanVideoReservesRow struct {
	BusinessAccountID string      `json:"business_account_id"`
	CorrelationID     string      `json:"correlation_id"`
	Amount            int64       `json:"amount"`
	ReferenceID       pgtype.Text `json:"reference_id"`
	CreatedAt         time.Time   `json:"created_at"`
}

// ============================================================================
// 5. orphan reserve sweep（跨表：ledger active reserve 反查无对应 task 行）
// ============================================================================
// orphan reserve sweep（6b / 计划 Unit 6 Approach）：扫 ledger 中尚未结算的视频任务 reserve
// （reference_type='video_task'）反查在 task 表无对应行者 → 调用方 Release 回退（无 orphan 占资金）。
//   - 未结算：同 reserve 既无 commit、也无 release（注意账本写入约定：commit entry 记在 base
//     correlation 下，**全额/残余 release entry 记在 correlation||':release' 下**——见 ledger
//     postgres.go Release/CommitWithReleaseAtomic）。故须同时排除两者，否则已被本 sweep（或正常
//     settleReleased）回退过的 reserve 因其 release 记在 ':release' 下而被反复误判为孤儿、每轮重扫。
//   - 无 task 行：reference_id（= 提交时的 task_id）在 task 表不存在 = reserve 落了但 task tx 没成。
//     reference_id IS NOT NULL 守卫：NULL 时 t.id = NULL 恒 false 会把 NULL-ref reserve 误判为孤儿。
//   - @max_created_at = now - 最小年龄阈值：**只回收确陈旧者**，避免误回收 in-flight 窗口内
//     「reserve 已落、claim+task tx 即将提交」的 reserve（否则该 task settle 反查不到 reserve →
//     ErrReserveNotFound → 资金锁死）。阈值须 ≫ reserve→task tx 正常间隔（计划 Risks）。
//
// 复用 idx_ledger_reference (reference_type, reference_id) 过滤 video_task（MVP 视频 ledger 行少）。
func (q *Queries) ScanOrphanVideoReserves(ctx context.Context, arg ScanOrphanVideoReservesParams) ([]ScanOrphanVideoReservesRow, error) {
	rows, err := q.db.Query(ctx, scanOrphanVideoReserves, arg.MaxCreatedAt, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanOrphanVideoReservesRow{}
	for rows.Next() {
		var i ScanOrphanVideoReservesRow
		if err := rows.Scan(
			&i.BusinessAccountID,
			&i.CorrelationID,
			&i.Amount,
			&i.ReferenceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanRecoverableTasks = `-- name: ScanRecoverableTasks :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status = 'UPSTREAM_SUBMITTING'
  AND submit_locked_until < $1
ORDER BY submit_locked_until
LIMIT $2
`

type ScanRecoverableTasksParams struct {
	Now       sql.NullTime `json:"now"`
	BatchSize int32        `json:"batch_size"`
}

// recover worker：扫 UPSTREAM_SUBMITTING 且 lease 过期的任务（崩溃在提交窗口）。
// ADR-0006 决策 5：上游无幂等键/不可反查 → 这些任务 fail-closed（不自动重投），
// 调用方据此 CAS→FAILED + release + 告警。用 idx_task_submit_recover。
func (q *Queries) ScanRecoverableTasks(ctx context.Context, arg ScanRecoverableTasksParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanRecoverableTasks, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanStuckSettling = `-- name: ScanStuckSettling :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status = 'SETTLING'
  AND updated_at < $1
ORDER BY updated_at
LIMIT $2
`

type ScanStuckSettlingParams struct {
	Threshold time.Time `json:"threshold"`
	BatchSize int32     `json:"batch_size"`
}

// fetch reconciler（6b）：扫 SETTLING 滞留超阈值的任务——硬崩溃于 commit/release 落账后、
// 终态 CAS（SETTLING→SETTLED/SETTLE_FAILED）前，task 卡 SETTLING（钱可能已落账、态未终）。
// 调用方幂等重投 settle 恢复：先反查 active reserve 判钱是否已落账，已落账→直接 finalize SETTLED，
// 未落账→按 error_code 判 COMPLETED/失败重走结算（靠账本 ErrAlreadySettled / 反查收敛）。
// 用 idx_task_stuck_settling（0009）。阈值须 ≫ 正常 settle 端到端耗时，避免抢正在结算中的任务。
func (q *Queries) ScanStuckSettling(ctx context.Context, arg ScanStuckSettlingParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanStuckSettling, arg.Threshold, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanStuckUpstreamSubmitted = `-- name: ScanStuckUpstreamSubmitted :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status = 'UPSTREAM_SUBMITTED'
  AND upstream_submitted_at < $1
ORDER BY upstream_submitted_at
LIMIT $2
`

type ScanStuckUpstreamSubmittedParams struct {
	Threshold sql.NullTime `json:"threshold"`
	BatchSize int32        `json:"batch_size"`
}

// fetch reconciler：扫 UPSTREAM_SUBMITTED 超时未终态的任务 → 主动 Poll 上游兜底。
func (q *Queries) ScanStuckUpstreamSubmitted(ctx context.Context, arg ScanStuckUpstreamSubmittedParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanStuckUpstreamSubmitted, arg.Threshold, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanSubmittedNoJob = `-- name: ScanSubmittedNoJob :many
SELECT id, business_account_id, token_id, channel_id, provider_type, model, status, upstream_task_id, submit_locked_until, submit_locked_by, submit_recover_count, financial_snapshot, accounting_month, submitted_at, terminal_at, error_code, error_message, updated_at, callback_token, upstream_submitted_at FROM task
WHERE status = 'SUBMITTED'
  AND submitted_at < $1
ORDER BY submitted_at
LIMIT $2
`

type ScanSubmittedNoJobParams struct {
	Threshold time.Time `json:"threshold"`
	BatchSize int32     `json:"batch_size"`
}

// reconciler：扫 SUBMITTED 滞留超阈值（入队丢失 / Redis 抖动导致无 Asynq job）→ 幂等重投。
func (q *Queries) ScanSubmittedNoJob(ctx context.Context, arg ScanSubmittedNoJobParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, scanSubmittedNoJob, arg.Threshold, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.BusinessAccountID,
			&i.TokenID,
			&i.ChannelID,
			&i.ProviderType,
			&i.Model,
			&i.Status,
			&i.UpstreamTaskID,
			&i.SubmitLockedUntil,
			&i.SubmitLockedBy,
			&i.SubmitRecoverCount,
			&i.FinancialSnapshot,
			&i.AccountingMonth,
			&i.SubmittedAt,
			&i.TerminalAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.UpdatedAt,
			&i.CallbackToken,
			&i.UpstreamSubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
